package com.compass.park.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ParkRuleSetBeanExample {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table TB_PARK_RULE_SET
     *
     * @ibatorgenerated Wed Nov 08 21:06:55 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table TB_PARK_RULE_SET
     *
     * @ibatorgenerated Wed Nov 08 21:06:55 CST 2017
     */
    protected List oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TB_PARK_RULE_SET
     *
     * @ibatorgenerated Wed Nov 08 21:06:55 CST 2017
     */
    public ParkRuleSetBeanExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TB_PARK_RULE_SET
     *
     * @ibatorgenerated Wed Nov 08 21:06:55 CST 2017
     */
    protected ParkRuleSetBeanExample(ParkRuleSetBeanExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TB_PARK_RULE_SET
     *
     * @ibatorgenerated Wed Nov 08 21:06:55 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TB_PARK_RULE_SET
     *
     * @ibatorgenerated Wed Nov 08 21:06:55 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TB_PARK_RULE_SET
     *
     * @ibatorgenerated Wed Nov 08 21:06:55 CST 2017
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TB_PARK_RULE_SET
     *
     * @ibatorgenerated Wed Nov 08 21:06:55 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TB_PARK_RULE_SET
     *
     * @ibatorgenerated Wed Nov 08 21:06:55 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TB_PARK_RULE_SET
     *
     * @ibatorgenerated Wed Nov 08 21:06:55 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TB_PARK_RULE_SET
     *
     * @ibatorgenerated Wed Nov 08 21:06:55 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table TB_PARK_RULE_SET
     *
     * @ibatorgenerated Wed Nov 08 21:06:55 CST 2017
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andParkRuleSetIdIsNull() {
            addCriterion("PARK_RULE_SET_ID is null");
            return this;
        }

        public Criteria andParkRuleSetIdIsNotNull() {
            addCriterion("PARK_RULE_SET_ID is not null");
            return this;
        }

        public Criteria andParkRuleSetIdEqualTo(String value) {
            addCriterion("PARK_RULE_SET_ID =", value, "parkRuleSetId");
            return this;
        }

        public Criteria andParkRuleSetIdNotEqualTo(String value) {
            addCriterion("PARK_RULE_SET_ID <>", value, "parkRuleSetId");
            return this;
        }

        public Criteria andParkRuleSetIdGreaterThan(String value) {
            addCriterion("PARK_RULE_SET_ID >", value, "parkRuleSetId");
            return this;
        }

        public Criteria andParkRuleSetIdGreaterThanOrEqualTo(String value) {
            addCriterion("PARK_RULE_SET_ID >=", value, "parkRuleSetId");
            return this;
        }

        public Criteria andParkRuleSetIdLessThan(String value) {
            addCriterion("PARK_RULE_SET_ID <", value, "parkRuleSetId");
            return this;
        }

        public Criteria andParkRuleSetIdLessThanOrEqualTo(String value) {
            addCriterion("PARK_RULE_SET_ID <=", value, "parkRuleSetId");
            return this;
        }

        public Criteria andParkRuleSetIdLike(String value) {
            addCriterion("PARK_RULE_SET_ID like", value, "parkRuleSetId");
            return this;
        }

        public Criteria andParkRuleSetIdNotLike(String value) {
            addCriterion("PARK_RULE_SET_ID not like", value, "parkRuleSetId");
            return this;
        }

        public Criteria andParkRuleSetIdIn(List values) {
            addCriterion("PARK_RULE_SET_ID in", values, "parkRuleSetId");
            return this;
        }

        public Criteria andParkRuleSetIdNotIn(List values) {
            addCriterion("PARK_RULE_SET_ID not in", values, "parkRuleSetId");
            return this;
        }

        public Criteria andParkRuleSetIdBetween(String value1, String value2) {
            addCriterion("PARK_RULE_SET_ID between", value1, value2, "parkRuleSetId");
            return this;
        }

        public Criteria andParkRuleSetIdNotBetween(String value1, String value2) {
            addCriterion("PARK_RULE_SET_ID not between", value1, value2, "parkRuleSetId");
            return this;
        }

        public Criteria andRuleNameIsNull() {
            addCriterion("RULE_NAME is null");
            return this;
        }

        public Criteria andRuleNameIsNotNull() {
            addCriterion("RULE_NAME is not null");
            return this;
        }

        public Criteria andRuleNameEqualTo(String value) {
            addCriterion("RULE_NAME =", value, "ruleName");
            return this;
        }

        public Criteria andRuleNameNotEqualTo(String value) {
            addCriterion("RULE_NAME <>", value, "ruleName");
            return this;
        }

        public Criteria andRuleNameGreaterThan(String value) {
            addCriterion("RULE_NAME >", value, "ruleName");
            return this;
        }

        public Criteria andRuleNameGreaterThanOrEqualTo(String value) {
            addCriterion("RULE_NAME >=", value, "ruleName");
            return this;
        }

        public Criteria andRuleNameLessThan(String value) {
            addCriterion("RULE_NAME <", value, "ruleName");
            return this;
        }

        public Criteria andRuleNameLessThanOrEqualTo(String value) {
            addCriterion("RULE_NAME <=", value, "ruleName");
            return this;
        }

        public Criteria andRuleNameLike(String value) {
            addCriterion("RULE_NAME like", value, "ruleName");
            return this;
        }

        public Criteria andRuleNameNotLike(String value) {
            addCriterion("RULE_NAME not like", value, "ruleName");
            return this;
        }

        public Criteria andRuleNameIn(List values) {
            addCriterion("RULE_NAME in", values, "ruleName");
            return this;
        }

        public Criteria andRuleNameNotIn(List values) {
            addCriterion("RULE_NAME not in", values, "ruleName");
            return this;
        }

        public Criteria andRuleNameBetween(String value1, String value2) {
            addCriterion("RULE_NAME between", value1, value2, "ruleName");
            return this;
        }

        public Criteria andRuleNameNotBetween(String value1, String value2) {
            addCriterion("RULE_NAME not between", value1, value2, "ruleName");
            return this;
        }

        public Criteria andVehicleTypeIsNull() {
            addCriterion("VEHICLE_TYPE is null");
            return this;
        }

        public Criteria andVehicleTypeIsNotNull() {
            addCriterion("VEHICLE_TYPE is not null");
            return this;
        }

        public Criteria andVehicleTypeEqualTo(String value) {
            addCriterion("VEHICLE_TYPE =", value, "vehicleType");
            return this;
        }

        public Criteria andVehicleTypeNotEqualTo(String value) {
            addCriterion("VEHICLE_TYPE <>", value, "vehicleType");
            return this;
        }

        public Criteria andVehicleTypeGreaterThan(String value) {
            addCriterion("VEHICLE_TYPE >", value, "vehicleType");
            return this;
        }

        public Criteria andVehicleTypeGreaterThanOrEqualTo(String value) {
            addCriterion("VEHICLE_TYPE >=", value, "vehicleType");
            return this;
        }

        public Criteria andVehicleTypeLessThan(String value) {
            addCriterion("VEHICLE_TYPE <", value, "vehicleType");
            return this;
        }

        public Criteria andVehicleTypeLessThanOrEqualTo(String value) {
            addCriterion("VEHICLE_TYPE <=", value, "vehicleType");
            return this;
        }

        public Criteria andVehicleTypeLike(String value) {
            addCriterion("VEHICLE_TYPE like", value, "vehicleType");
            return this;
        }

        public Criteria andVehicleTypeNotLike(String value) {
            addCriterion("VEHICLE_TYPE not like", value, "vehicleType");
            return this;
        }

        public Criteria andVehicleTypeIn(List values) {
            addCriterion("VEHICLE_TYPE in", values, "vehicleType");
            return this;
        }

        public Criteria andVehicleTypeNotIn(List values) {
            addCriterion("VEHICLE_TYPE not in", values, "vehicleType");
            return this;
        }

        public Criteria andVehicleTypeBetween(String value1, String value2) {
            addCriterion("VEHICLE_TYPE between", value1, value2, "vehicleType");
            return this;
        }

        public Criteria andVehicleTypeNotBetween(String value1, String value2) {
            addCriterion("VEHICLE_TYPE not between", value1, value2, "vehicleType");
            return this;
        }

        public Criteria andOutParkingIdIsNull() {
            addCriterion("OUT_PARKING_ID is null");
            return this;
        }

        public Criteria andOutParkingIdIsNotNull() {
            addCriterion("OUT_PARKING_ID is not null");
            return this;
        }

        public Criteria andOutParkingIdEqualTo(String value) {
            addCriterion("OUT_PARKING_ID =", value, "outParkingId");
            return this;
        }

        public Criteria andOutParkingIdNotEqualTo(String value) {
            addCriterion("OUT_PARKING_ID <>", value, "outParkingId");
            return this;
        }

        public Criteria andOutParkingIdGreaterThan(String value) {
            addCriterion("OUT_PARKING_ID >", value, "outParkingId");
            return this;
        }

        public Criteria andOutParkingIdGreaterThanOrEqualTo(String value) {
            addCriterion("OUT_PARKING_ID >=", value, "outParkingId");
            return this;
        }

        public Criteria andOutParkingIdLessThan(String value) {
            addCriterion("OUT_PARKING_ID <", value, "outParkingId");
            return this;
        }

        public Criteria andOutParkingIdLessThanOrEqualTo(String value) {
            addCriterion("OUT_PARKING_ID <=", value, "outParkingId");
            return this;
        }

        public Criteria andOutParkingIdLike(String value) {
            addCriterion("OUT_PARKING_ID like", value, "outParkingId");
            return this;
        }

        public Criteria andOutParkingIdNotLike(String value) {
            addCriterion("OUT_PARKING_ID not like", value, "outParkingId");
            return this;
        }

        public Criteria andOutParkingIdIn(List values) {
            addCriterion("OUT_PARKING_ID in", values, "outParkingId");
            return this;
        }

        public Criteria andOutParkingIdNotIn(List values) {
            addCriterion("OUT_PARKING_ID not in", values, "outParkingId");
            return this;
        }

        public Criteria andOutParkingIdBetween(String value1, String value2) {
            addCriterion("OUT_PARKING_ID between", value1, value2, "outParkingId");
            return this;
        }

        public Criteria andOutParkingIdNotBetween(String value1, String value2) {
            addCriterion("OUT_PARKING_ID not between", value1, value2, "outParkingId");
            return this;
        }

        public Criteria andDayLimitIsNull() {
            addCriterion("DAY_LIMIT is null");
            return this;
        }

        public Criteria andDayLimitIsNotNull() {
            addCriterion("DAY_LIMIT is not null");
            return this;
        }

        public Criteria andDayLimitEqualTo(BigDecimal value) {
            addCriterion("DAY_LIMIT =", value, "dayLimit");
            return this;
        }

        public Criteria andDayLimitNotEqualTo(BigDecimal value) {
            addCriterion("DAY_LIMIT <>", value, "dayLimit");
            return this;
        }

        public Criteria andDayLimitGreaterThan(BigDecimal value) {
            addCriterion("DAY_LIMIT >", value, "dayLimit");
            return this;
        }

        public Criteria andDayLimitGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("DAY_LIMIT >=", value, "dayLimit");
            return this;
        }

        public Criteria andDayLimitLessThan(BigDecimal value) {
            addCriterion("DAY_LIMIT <", value, "dayLimit");
            return this;
        }

        public Criteria andDayLimitLessThanOrEqualTo(BigDecimal value) {
            addCriterion("DAY_LIMIT <=", value, "dayLimit");
            return this;
        }

        public Criteria andDayLimitIn(List values) {
            addCriterion("DAY_LIMIT in", values, "dayLimit");
            return this;
        }

        public Criteria andDayLimitNotIn(List values) {
            addCriterion("DAY_LIMIT not in", values, "dayLimit");
            return this;
        }

        public Criteria andDayLimitBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("DAY_LIMIT between", value1, value2, "dayLimit");
            return this;
        }

        public Criteria andDayLimitNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("DAY_LIMIT not between", value1, value2, "dayLimit");
            return this;
        }

        public Criteria andStartHourIsNull() {
            addCriterion("START_HOUR is null");
            return this;
        }

        public Criteria andStartHourIsNotNull() {
            addCriterion("START_HOUR is not null");
            return this;
        }

        public Criteria andStartHourEqualTo(String value) {
            addCriterion("START_HOUR =", value, "startHour");
            return this;
        }

        public Criteria andStartHourNotEqualTo(String value) {
            addCriterion("START_HOUR <>", value, "startHour");
            return this;
        }

        public Criteria andStartHourGreaterThan(String value) {
            addCriterion("START_HOUR >", value, "startHour");
            return this;
        }

        public Criteria andStartHourGreaterThanOrEqualTo(String value) {
            addCriterion("START_HOUR >=", value, "startHour");
            return this;
        }

        public Criteria andStartHourLessThan(String value) {
            addCriterion("START_HOUR <", value, "startHour");
            return this;
        }

        public Criteria andStartHourLessThanOrEqualTo(String value) {
            addCriterion("START_HOUR <=", value, "startHour");
            return this;
        }

        public Criteria andStartHourLike(String value) {
            addCriterion("START_HOUR like", value, "startHour");
            return this;
        }

        public Criteria andStartHourNotLike(String value) {
            addCriterion("START_HOUR not like", value, "startHour");
            return this;
        }

        public Criteria andStartHourIn(List values) {
            addCriterion("START_HOUR in", values, "startHour");
            return this;
        }

        public Criteria andStartHourNotIn(List values) {
            addCriterion("START_HOUR not in", values, "startHour");
            return this;
        }

        public Criteria andStartHourBetween(String value1, String value2) {
            addCriterion("START_HOUR between", value1, value2, "startHour");
            return this;
        }

        public Criteria andStartHourNotBetween(String value1, String value2) {
            addCriterion("START_HOUR not between", value1, value2, "startHour");
            return this;
        }

        public Criteria andEndHourIsNull() {
            addCriterion("END_HOUR is null");
            return this;
        }

        public Criteria andEndHourIsNotNull() {
            addCriterion("END_HOUR is not null");
            return this;
        }

        public Criteria andEndHourEqualTo(String value) {
            addCriterion("END_HOUR =", value, "endHour");
            return this;
        }

        public Criteria andEndHourNotEqualTo(String value) {
            addCriterion("END_HOUR <>", value, "endHour");
            return this;
        }

        public Criteria andEndHourGreaterThan(String value) {
            addCriterion("END_HOUR >", value, "endHour");
            return this;
        }

        public Criteria andEndHourGreaterThanOrEqualTo(String value) {
            addCriterion("END_HOUR >=", value, "endHour");
            return this;
        }

        public Criteria andEndHourLessThan(String value) {
            addCriterion("END_HOUR <", value, "endHour");
            return this;
        }

        public Criteria andEndHourLessThanOrEqualTo(String value) {
            addCriterion("END_HOUR <=", value, "endHour");
            return this;
        }

        public Criteria andEndHourLike(String value) {
            addCriterion("END_HOUR like", value, "endHour");
            return this;
        }

        public Criteria andEndHourNotLike(String value) {
            addCriterion("END_HOUR not like", value, "endHour");
            return this;
        }

        public Criteria andEndHourIn(List values) {
            addCriterion("END_HOUR in", values, "endHour");
            return this;
        }

        public Criteria andEndHourNotIn(List values) {
            addCriterion("END_HOUR not in", values, "endHour");
            return this;
        }

        public Criteria andEndHourBetween(String value1, String value2) {
            addCriterion("END_HOUR between", value1, value2, "endHour");
            return this;
        }

        public Criteria andEndHourNotBetween(String value1, String value2) {
            addCriterion("END_HOUR not between", value1, value2, "endHour");
            return this;
        }

        public Criteria andDateSetIsNull() {
            addCriterion("DATE_SET is null");
            return this;
        }

        public Criteria andDateSetIsNotNull() {
            addCriterion("DATE_SET is not null");
            return this;
        }

        public Criteria andDateSetEqualTo(String value) {
            addCriterion("DATE_SET =", value, "dateSet");
            return this;
        }

        public Criteria andDateSetNotEqualTo(String value) {
            addCriterion("DATE_SET <>", value, "dateSet");
            return this;
        }

        public Criteria andDateSetGreaterThan(String value) {
            addCriterion("DATE_SET >", value, "dateSet");
            return this;
        }

        public Criteria andDateSetGreaterThanOrEqualTo(String value) {
            addCriterion("DATE_SET >=", value, "dateSet");
            return this;
        }

        public Criteria andDateSetLessThan(String value) {
            addCriterion("DATE_SET <", value, "dateSet");
            return this;
        }

        public Criteria andDateSetLessThanOrEqualTo(String value) {
            addCriterion("DATE_SET <=", value, "dateSet");
            return this;
        }

        public Criteria andDateSetLike(String value) {
            addCriterion("DATE_SET like", value, "dateSet");
            return this;
        }

        public Criteria andDateSetNotLike(String value) {
            addCriterion("DATE_SET not like", value, "dateSet");
            return this;
        }

        public Criteria andDateSetIn(List values) {
            addCriterion("DATE_SET in", values, "dateSet");
            return this;
        }

        public Criteria andDateSetNotIn(List values) {
            addCriterion("DATE_SET not in", values, "dateSet");
            return this;
        }

        public Criteria andDateSetBetween(String value1, String value2) {
            addCriterion("DATE_SET between", value1, value2, "dateSet");
            return this;
        }

        public Criteria andDateSetNotBetween(String value1, String value2) {
            addCriterion("DATE_SET not between", value1, value2, "dateSet");
            return this;
        }

        public Criteria andChargeTypeIsNull() {
            addCriterion("CHARGE_TYPE is null");
            return this;
        }

        public Criteria andChargeTypeIsNotNull() {
            addCriterion("CHARGE_TYPE is not null");
            return this;
        }

        public Criteria andChargeTypeEqualTo(String value) {
            addCriterion("CHARGE_TYPE =", value, "chargeType");
            return this;
        }

        public Criteria andChargeTypeNotEqualTo(String value) {
            addCriterion("CHARGE_TYPE <>", value, "chargeType");
            return this;
        }

        public Criteria andChargeTypeGreaterThan(String value) {
            addCriterion("CHARGE_TYPE >", value, "chargeType");
            return this;
        }

        public Criteria andChargeTypeGreaterThanOrEqualTo(String value) {
            addCriterion("CHARGE_TYPE >=", value, "chargeType");
            return this;
        }

        public Criteria andChargeTypeLessThan(String value) {
            addCriterion("CHARGE_TYPE <", value, "chargeType");
            return this;
        }

        public Criteria andChargeTypeLessThanOrEqualTo(String value) {
            addCriterion("CHARGE_TYPE <=", value, "chargeType");
            return this;
        }

        public Criteria andChargeTypeLike(String value) {
            addCriterion("CHARGE_TYPE like", value, "chargeType");
            return this;
        }

        public Criteria andChargeTypeNotLike(String value) {
            addCriterion("CHARGE_TYPE not like", value, "chargeType");
            return this;
        }

        public Criteria andChargeTypeIn(List values) {
            addCriterion("CHARGE_TYPE in", values, "chargeType");
            return this;
        }

        public Criteria andChargeTypeNotIn(List values) {
            addCriterion("CHARGE_TYPE not in", values, "chargeType");
            return this;
        }

        public Criteria andChargeTypeBetween(String value1, String value2) {
            addCriterion("CHARGE_TYPE between", value1, value2, "chargeType");
            return this;
        }

        public Criteria andChargeTypeNotBetween(String value1, String value2) {
            addCriterion("CHARGE_TYPE not between", value1, value2, "chargeType");
            return this;
        }

        public Criteria andFreeTimeIsNull() {
            addCriterion("FREE_TIME is null");
            return this;
        }

        public Criteria andFreeTimeIsNotNull() {
            addCriterion("FREE_TIME is not null");
            return this;
        }

        public Criteria andFreeTimeEqualTo(Long value) {
            addCriterion("FREE_TIME =", value, "freeTime");
            return this;
        }

        public Criteria andFreeTimeNotEqualTo(Long value) {
            addCriterion("FREE_TIME <>", value, "freeTime");
            return this;
        }

        public Criteria andFreeTimeGreaterThan(Long value) {
            addCriterion("FREE_TIME >", value, "freeTime");
            return this;
        }

        public Criteria andFreeTimeGreaterThanOrEqualTo(Long value) {
            addCriterion("FREE_TIME >=", value, "freeTime");
            return this;
        }

        public Criteria andFreeTimeLessThan(Long value) {
            addCriterion("FREE_TIME <", value, "freeTime");
            return this;
        }

        public Criteria andFreeTimeLessThanOrEqualTo(Long value) {
            addCriterion("FREE_TIME <=", value, "freeTime");
            return this;
        }

        public Criteria andFreeTimeIn(List values) {
            addCriterion("FREE_TIME in", values, "freeTime");
            return this;
        }

        public Criteria andFreeTimeNotIn(List values) {
            addCriterion("FREE_TIME not in", values, "freeTime");
            return this;
        }

        public Criteria andFreeTimeBetween(Long value1, Long value2) {
            addCriterion("FREE_TIME between", value1, value2, "freeTime");
            return this;
        }

        public Criteria andFreeTimeNotBetween(Long value1, Long value2) {
            addCriterion("FREE_TIME not between", value1, value2, "freeTime");
            return this;
        }

        public Criteria andSubChargeIsNull() {
            addCriterion("SUB_CHARGE is null");
            return this;
        }

        public Criteria andSubChargeIsNotNull() {
            addCriterion("SUB_CHARGE is not null");
            return this;
        }

        public Criteria andSubChargeEqualTo(BigDecimal value) {
            addCriterion("SUB_CHARGE =", value, "subCharge");
            return this;
        }

        public Criteria andSubChargeNotEqualTo(BigDecimal value) {
            addCriterion("SUB_CHARGE <>", value, "subCharge");
            return this;
        }

        public Criteria andSubChargeGreaterThan(BigDecimal value) {
            addCriterion("SUB_CHARGE >", value, "subCharge");
            return this;
        }

        public Criteria andSubChargeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("SUB_CHARGE >=", value, "subCharge");
            return this;
        }

        public Criteria andSubChargeLessThan(BigDecimal value) {
            addCriterion("SUB_CHARGE <", value, "subCharge");
            return this;
        }

        public Criteria andSubChargeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("SUB_CHARGE <=", value, "subCharge");
            return this;
        }

        public Criteria andSubChargeIn(List values) {
            addCriterion("SUB_CHARGE in", values, "subCharge");
            return this;
        }

        public Criteria andSubChargeNotIn(List values) {
            addCriterion("SUB_CHARGE not in", values, "subCharge");
            return this;
        }

        public Criteria andSubChargeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SUB_CHARGE between", value1, value2, "subCharge");
            return this;
        }

        public Criteria andSubChargeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SUB_CHARGE not between", value1, value2, "subCharge");
            return this;
        }

        public Criteria andTimeSlotLimitIsNull() {
            addCriterion("TIME_SLOT_LIMIT is null");
            return this;
        }

        public Criteria andTimeSlotLimitIsNotNull() {
            addCriterion("TIME_SLOT_LIMIT is not null");
            return this;
        }

        public Criteria andTimeSlotLimitEqualTo(BigDecimal value) {
            addCriterion("TIME_SLOT_LIMIT =", value, "timeSlotLimit");
            return this;
        }

        public Criteria andTimeSlotLimitNotEqualTo(BigDecimal value) {
            addCriterion("TIME_SLOT_LIMIT <>", value, "timeSlotLimit");
            return this;
        }

        public Criteria andTimeSlotLimitGreaterThan(BigDecimal value) {
            addCriterion("TIME_SLOT_LIMIT >", value, "timeSlotLimit");
            return this;
        }

        public Criteria andTimeSlotLimitGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("TIME_SLOT_LIMIT >=", value, "timeSlotLimit");
            return this;
        }

        public Criteria andTimeSlotLimitLessThan(BigDecimal value) {
            addCriterion("TIME_SLOT_LIMIT <", value, "timeSlotLimit");
            return this;
        }

        public Criteria andTimeSlotLimitLessThanOrEqualTo(BigDecimal value) {
            addCriterion("TIME_SLOT_LIMIT <=", value, "timeSlotLimit");
            return this;
        }

        public Criteria andTimeSlotLimitIn(List values) {
            addCriterion("TIME_SLOT_LIMIT in", values, "timeSlotLimit");
            return this;
        }

        public Criteria andTimeSlotLimitNotIn(List values) {
            addCriterion("TIME_SLOT_LIMIT not in", values, "timeSlotLimit");
            return this;
        }

        public Criteria andTimeSlotLimitBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TIME_SLOT_LIMIT between", value1, value2, "timeSlotLimit");
            return this;
        }

        public Criteria andTimeSlotLimitNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TIME_SLOT_LIMIT not between", value1, value2, "timeSlotLimit");
            return this;
        }

        public Criteria andStartChargeTimeIsNull() {
            addCriterion("START_CHARGE_TIME is null");
            return this;
        }

        public Criteria andStartChargeTimeIsNotNull() {
            addCriterion("START_CHARGE_TIME is not null");
            return this;
        }

        public Criteria andStartChargeTimeEqualTo(Long value) {
            addCriterion("START_CHARGE_TIME =", value, "startChargeTime");
            return this;
        }

        public Criteria andStartChargeTimeNotEqualTo(Long value) {
            addCriterion("START_CHARGE_TIME <>", value, "startChargeTime");
            return this;
        }

        public Criteria andStartChargeTimeGreaterThan(Long value) {
            addCriterion("START_CHARGE_TIME >", value, "startChargeTime");
            return this;
        }

        public Criteria andStartChargeTimeGreaterThanOrEqualTo(Long value) {
            addCriterion("START_CHARGE_TIME >=", value, "startChargeTime");
            return this;
        }

        public Criteria andStartChargeTimeLessThan(Long value) {
            addCriterion("START_CHARGE_TIME <", value, "startChargeTime");
            return this;
        }

        public Criteria andStartChargeTimeLessThanOrEqualTo(Long value) {
            addCriterion("START_CHARGE_TIME <=", value, "startChargeTime");
            return this;
        }

        public Criteria andStartChargeTimeIn(List values) {
            addCriterion("START_CHARGE_TIME in", values, "startChargeTime");
            return this;
        }

        public Criteria andStartChargeTimeNotIn(List values) {
            addCriterion("START_CHARGE_TIME not in", values, "startChargeTime");
            return this;
        }

        public Criteria andStartChargeTimeBetween(Long value1, Long value2) {
            addCriterion("START_CHARGE_TIME between", value1, value2, "startChargeTime");
            return this;
        }

        public Criteria andStartChargeTimeNotBetween(Long value1, Long value2) {
            addCriterion("START_CHARGE_TIME not between", value1, value2, "startChargeTime");
            return this;
        }

        public Criteria andStartChargePriceIsNull() {
            addCriterion("START_CHARGE_PRICE is null");
            return this;
        }

        public Criteria andStartChargePriceIsNotNull() {
            addCriterion("START_CHARGE_PRICE is not null");
            return this;
        }

        public Criteria andStartChargePriceEqualTo(BigDecimal value) {
            addCriterion("START_CHARGE_PRICE =", value, "startChargePrice");
            return this;
        }

        public Criteria andStartChargePriceNotEqualTo(BigDecimal value) {
            addCriterion("START_CHARGE_PRICE <>", value, "startChargePrice");
            return this;
        }

        public Criteria andStartChargePriceGreaterThan(BigDecimal value) {
            addCriterion("START_CHARGE_PRICE >", value, "startChargePrice");
            return this;
        }

        public Criteria andStartChargePriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("START_CHARGE_PRICE >=", value, "startChargePrice");
            return this;
        }

        public Criteria andStartChargePriceLessThan(BigDecimal value) {
            addCriterion("START_CHARGE_PRICE <", value, "startChargePrice");
            return this;
        }

        public Criteria andStartChargePriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("START_CHARGE_PRICE <=", value, "startChargePrice");
            return this;
        }

        public Criteria andStartChargePriceIn(List values) {
            addCriterion("START_CHARGE_PRICE in", values, "startChargePrice");
            return this;
        }

        public Criteria andStartChargePriceNotIn(List values) {
            addCriterion("START_CHARGE_PRICE not in", values, "startChargePrice");
            return this;
        }

        public Criteria andStartChargePriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("START_CHARGE_PRICE between", value1, value2, "startChargePrice");
            return this;
        }

        public Criteria andStartChargePriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("START_CHARGE_PRICE not between", value1, value2, "startChargePrice");
            return this;
        }

        public Criteria andChargeTimeIsNull() {
            addCriterion("CHARGE_TIME is null");
            return this;
        }

        public Criteria andChargeTimeIsNotNull() {
            addCriterion("CHARGE_TIME is not null");
            return this;
        }

        public Criteria andChargeTimeEqualTo(Long value) {
            addCriterion("CHARGE_TIME =", value, "chargeTime");
            return this;
        }

        public Criteria andChargeTimeNotEqualTo(Long value) {
            addCriterion("CHARGE_TIME <>", value, "chargeTime");
            return this;
        }

        public Criteria andChargeTimeGreaterThan(Long value) {
            addCriterion("CHARGE_TIME >", value, "chargeTime");
            return this;
        }

        public Criteria andChargeTimeGreaterThanOrEqualTo(Long value) {
            addCriterion("CHARGE_TIME >=", value, "chargeTime");
            return this;
        }

        public Criteria andChargeTimeLessThan(Long value) {
            addCriterion("CHARGE_TIME <", value, "chargeTime");
            return this;
        }

        public Criteria andChargeTimeLessThanOrEqualTo(Long value) {
            addCriterion("CHARGE_TIME <=", value, "chargeTime");
            return this;
        }

        public Criteria andChargeTimeIn(List values) {
            addCriterion("CHARGE_TIME in", values, "chargeTime");
            return this;
        }

        public Criteria andChargeTimeNotIn(List values) {
            addCriterion("CHARGE_TIME not in", values, "chargeTime");
            return this;
        }

        public Criteria andChargeTimeBetween(Long value1, Long value2) {
            addCriterion("CHARGE_TIME between", value1, value2, "chargeTime");
            return this;
        }

        public Criteria andChargeTimeNotBetween(Long value1, Long value2) {
            addCriterion("CHARGE_TIME not between", value1, value2, "chargeTime");
            return this;
        }

        public Criteria andChargePriceIsNull() {
            addCriterion("CHARGE_PRICE is null");
            return this;
        }

        public Criteria andChargePriceIsNotNull() {
            addCriterion("CHARGE_PRICE is not null");
            return this;
        }

        public Criteria andChargePriceEqualTo(BigDecimal value) {
            addCriterion("CHARGE_PRICE =", value, "chargePrice");
            return this;
        }

        public Criteria andChargePriceNotEqualTo(BigDecimal value) {
            addCriterion("CHARGE_PRICE <>", value, "chargePrice");
            return this;
        }

        public Criteria andChargePriceGreaterThan(BigDecimal value) {
            addCriterion("CHARGE_PRICE >", value, "chargePrice");
            return this;
        }

        public Criteria andChargePriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("CHARGE_PRICE >=", value, "chargePrice");
            return this;
        }

        public Criteria andChargePriceLessThan(BigDecimal value) {
            addCriterion("CHARGE_PRICE <", value, "chargePrice");
            return this;
        }

        public Criteria andChargePriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("CHARGE_PRICE <=", value, "chargePrice");
            return this;
        }

        public Criteria andChargePriceIn(List values) {
            addCriterion("CHARGE_PRICE in", values, "chargePrice");
            return this;
        }

        public Criteria andChargePriceNotIn(List values) {
            addCriterion("CHARGE_PRICE not in", values, "chargePrice");
            return this;
        }

        public Criteria andChargePriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CHARGE_PRICE between", value1, value2, "chargePrice");
            return this;
        }

        public Criteria andChargePriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CHARGE_PRICE not between", value1, value2, "chargePrice");
            return this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("STATUS =", value, "status");
            return this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("STATUS <>", value, "status");
            return this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("STATUS >", value, "status");
            return this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("STATUS >=", value, "status");
            return this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("STATUS <", value, "status");
            return this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("STATUS <=", value, "status");
            return this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("STATUS like", value, "status");
            return this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("STATUS not like", value, "status");
            return this;
        }

        public Criteria andStatusIn(List values) {
            addCriterion("STATUS in", values, "status");
            return this;
        }

        public Criteria andStatusNotIn(List values) {
            addCriterion("STATUS not in", values, "status");
            return this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return this;
        }

        public Criteria andCreateUseridIsNull() {
            addCriterion("CREATE_USERID is null");
            return this;
        }

        public Criteria andCreateUseridIsNotNull() {
            addCriterion("CREATE_USERID is not null");
            return this;
        }

        public Criteria andCreateUseridEqualTo(String value) {
            addCriterion("CREATE_USERID =", value, "createUserid");
            return this;
        }

        public Criteria andCreateUseridNotEqualTo(String value) {
            addCriterion("CREATE_USERID <>", value, "createUserid");
            return this;
        }

        public Criteria andCreateUseridGreaterThan(String value) {
            addCriterion("CREATE_USERID >", value, "createUserid");
            return this;
        }

        public Criteria andCreateUseridGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_USERID >=", value, "createUserid");
            return this;
        }

        public Criteria andCreateUseridLessThan(String value) {
            addCriterion("CREATE_USERID <", value, "createUserid");
            return this;
        }

        public Criteria andCreateUseridLessThanOrEqualTo(String value) {
            addCriterion("CREATE_USERID <=", value, "createUserid");
            return this;
        }

        public Criteria andCreateUseridLike(String value) {
            addCriterion("CREATE_USERID like", value, "createUserid");
            return this;
        }

        public Criteria andCreateUseridNotLike(String value) {
            addCriterion("CREATE_USERID not like", value, "createUserid");
            return this;
        }

        public Criteria andCreateUseridIn(List values) {
            addCriterion("CREATE_USERID in", values, "createUserid");
            return this;
        }

        public Criteria andCreateUseridNotIn(List values) {
            addCriterion("CREATE_USERID not in", values, "createUserid");
            return this;
        }

        public Criteria andCreateUseridBetween(String value1, String value2) {
            addCriterion("CREATE_USERID between", value1, value2, "createUserid");
            return this;
        }

        public Criteria andCreateUseridNotBetween(String value1, String value2) {
            addCriterion("CREATE_USERID not between", value1, value2, "createUserid");
            return this;
        }

        public Criteria andModifyUseridIsNull() {
            addCriterion("MODIFY_USERID is null");
            return this;
        }

        public Criteria andModifyUseridIsNotNull() {
            addCriterion("MODIFY_USERID is not null");
            return this;
        }

        public Criteria andModifyUseridEqualTo(String value) {
            addCriterion("MODIFY_USERID =", value, "modifyUserid");
            return this;
        }

        public Criteria andModifyUseridNotEqualTo(String value) {
            addCriterion("MODIFY_USERID <>", value, "modifyUserid");
            return this;
        }

        public Criteria andModifyUseridGreaterThan(String value) {
            addCriterion("MODIFY_USERID >", value, "modifyUserid");
            return this;
        }

        public Criteria andModifyUseridGreaterThanOrEqualTo(String value) {
            addCriterion("MODIFY_USERID >=", value, "modifyUserid");
            return this;
        }

        public Criteria andModifyUseridLessThan(String value) {
            addCriterion("MODIFY_USERID <", value, "modifyUserid");
            return this;
        }

        public Criteria andModifyUseridLessThanOrEqualTo(String value) {
            addCriterion("MODIFY_USERID <=", value, "modifyUserid");
            return this;
        }

        public Criteria andModifyUseridLike(String value) {
            addCriterion("MODIFY_USERID like", value, "modifyUserid");
            return this;
        }

        public Criteria andModifyUseridNotLike(String value) {
            addCriterion("MODIFY_USERID not like", value, "modifyUserid");
            return this;
        }

        public Criteria andModifyUseridIn(List values) {
            addCriterion("MODIFY_USERID in", values, "modifyUserid");
            return this;
        }

        public Criteria andModifyUseridNotIn(List values) {
            addCriterion("MODIFY_USERID not in", values, "modifyUserid");
            return this;
        }

        public Criteria andModifyUseridBetween(String value1, String value2) {
            addCriterion("MODIFY_USERID between", value1, value2, "modifyUserid");
            return this;
        }

        public Criteria andModifyUseridNotBetween(String value1, String value2) {
            addCriterion("MODIFY_USERID not between", value1, value2, "modifyUserid");
            return this;
        }

        public Criteria andCreateDatetimeIsNull() {
            addCriterion("CREATE_DATETIME is null");
            return this;
        }

        public Criteria andCreateDatetimeIsNotNull() {
            addCriterion("CREATE_DATETIME is not null");
            return this;
        }

        public Criteria andCreateDatetimeEqualTo(Date value) {
            addCriterion("CREATE_DATETIME =", value, "createDatetime");
            return this;
        }

        public Criteria andCreateDatetimeNotEqualTo(Date value) {
            addCriterion("CREATE_DATETIME <>", value, "createDatetime");
            return this;
        }

        public Criteria andCreateDatetimeGreaterThan(Date value) {
            addCriterion("CREATE_DATETIME >", value, "createDatetime");
            return this;
        }

        public Criteria andCreateDatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATETIME >=", value, "createDatetime");
            return this;
        }

        public Criteria andCreateDatetimeLessThan(Date value) {
            addCriterion("CREATE_DATETIME <", value, "createDatetime");
            return this;
        }

        public Criteria andCreateDatetimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATETIME <=", value, "createDatetime");
            return this;
        }

        public Criteria andCreateDatetimeIn(List values) {
            addCriterion("CREATE_DATETIME in", values, "createDatetime");
            return this;
        }

        public Criteria andCreateDatetimeNotIn(List values) {
            addCriterion("CREATE_DATETIME not in", values, "createDatetime");
            return this;
        }

        public Criteria andCreateDatetimeBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATETIME between", value1, value2, "createDatetime");
            return this;
        }

        public Criteria andCreateDatetimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATETIME not between", value1, value2, "createDatetime");
            return this;
        }

        public Criteria andModifyDatetimeIsNull() {
            addCriterion("MODIFY_DATETIME is null");
            return this;
        }

        public Criteria andModifyDatetimeIsNotNull() {
            addCriterion("MODIFY_DATETIME is not null");
            return this;
        }

        public Criteria andModifyDatetimeEqualTo(Date value) {
            addCriterion("MODIFY_DATETIME =", value, "modifyDatetime");
            return this;
        }

        public Criteria andModifyDatetimeNotEqualTo(Date value) {
            addCriterion("MODIFY_DATETIME <>", value, "modifyDatetime");
            return this;
        }

        public Criteria andModifyDatetimeGreaterThan(Date value) {
            addCriterion("MODIFY_DATETIME >", value, "modifyDatetime");
            return this;
        }

        public Criteria andModifyDatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("MODIFY_DATETIME >=", value, "modifyDatetime");
            return this;
        }

        public Criteria andModifyDatetimeLessThan(Date value) {
            addCriterion("MODIFY_DATETIME <", value, "modifyDatetime");
            return this;
        }

        public Criteria andModifyDatetimeLessThanOrEqualTo(Date value) {
            addCriterion("MODIFY_DATETIME <=", value, "modifyDatetime");
            return this;
        }

        public Criteria andModifyDatetimeIn(List values) {
            addCriterion("MODIFY_DATETIME in", values, "modifyDatetime");
            return this;
        }

        public Criteria andModifyDatetimeNotIn(List values) {
            addCriterion("MODIFY_DATETIME not in", values, "modifyDatetime");
            return this;
        }

        public Criteria andModifyDatetimeBetween(Date value1, Date value2) {
            addCriterion("MODIFY_DATETIME between", value1, value2, "modifyDatetime");
            return this;
        }

        public Criteria andModifyDatetimeNotBetween(Date value1, Date value2) {
            addCriterion("MODIFY_DATETIME not between", value1, value2, "modifyDatetime");
            return this;
        }

        public Criteria andNChargeTypeIsNull() {
            addCriterion("N_CHARGE_TYPE is null");
            return this;
        }

        public Criteria andNChargeTypeIsNotNull() {
            addCriterion("N_CHARGE_TYPE is not null");
            return this;
        }

        public Criteria andNChargeTypeEqualTo(String value) {
            addCriterion("N_CHARGE_TYPE =", value, "nChargeType");
            return this;
        }

        public Criteria andNChargeTypeNotEqualTo(String value) {
            addCriterion("N_CHARGE_TYPE <>", value, "nChargeType");
            return this;
        }

        public Criteria andNChargeTypeGreaterThan(String value) {
            addCriterion("N_CHARGE_TYPE >", value, "nChargeType");
            return this;
        }

        public Criteria andNChargeTypeGreaterThanOrEqualTo(String value) {
            addCriterion("N_CHARGE_TYPE >=", value, "nChargeType");
            return this;
        }

        public Criteria andNChargeTypeLessThan(String value) {
            addCriterion("N_CHARGE_TYPE <", value, "nChargeType");
            return this;
        }

        public Criteria andNChargeTypeLessThanOrEqualTo(String value) {
            addCriterion("N_CHARGE_TYPE <=", value, "nChargeType");
            return this;
        }

        public Criteria andNChargeTypeLike(String value) {
            addCriterion("N_CHARGE_TYPE like", value, "nChargeType");
            return this;
        }

        public Criteria andNChargeTypeNotLike(String value) {
            addCriterion("N_CHARGE_TYPE not like", value, "nChargeType");
            return this;
        }

        public Criteria andNChargeTypeIn(List values) {
            addCriterion("N_CHARGE_TYPE in", values, "nChargeType");
            return this;
        }

        public Criteria andNChargeTypeNotIn(List values) {
            addCriterion("N_CHARGE_TYPE not in", values, "nChargeType");
            return this;
        }

        public Criteria andNChargeTypeBetween(String value1, String value2) {
            addCriterion("N_CHARGE_TYPE between", value1, value2, "nChargeType");
            return this;
        }

        public Criteria andNChargeTypeNotBetween(String value1, String value2) {
            addCriterion("N_CHARGE_TYPE not between", value1, value2, "nChargeType");
            return this;
        }

        public Criteria andNFreeTimeIsNull() {
            addCriterion("N_FREE_TIME is null");
            return this;
        }

        public Criteria andNFreeTimeIsNotNull() {
            addCriterion("N_FREE_TIME is not null");
            return this;
        }

        public Criteria andNFreeTimeEqualTo(Long value) {
            addCriterion("N_FREE_TIME =", value, "nFreeTime");
            return this;
        }

        public Criteria andNFreeTimeNotEqualTo(Long value) {
            addCriterion("N_FREE_TIME <>", value, "nFreeTime");
            return this;
        }

        public Criteria andNFreeTimeGreaterThan(Long value) {
            addCriterion("N_FREE_TIME >", value, "nFreeTime");
            return this;
        }

        public Criteria andNFreeTimeGreaterThanOrEqualTo(Long value) {
            addCriterion("N_FREE_TIME >=", value, "nFreeTime");
            return this;
        }

        public Criteria andNFreeTimeLessThan(Long value) {
            addCriterion("N_FREE_TIME <", value, "nFreeTime");
            return this;
        }

        public Criteria andNFreeTimeLessThanOrEqualTo(Long value) {
            addCriterion("N_FREE_TIME <=", value, "nFreeTime");
            return this;
        }

        public Criteria andNFreeTimeIn(List values) {
            addCriterion("N_FREE_TIME in", values, "nFreeTime");
            return this;
        }

        public Criteria andNFreeTimeNotIn(List values) {
            addCriterion("N_FREE_TIME not in", values, "nFreeTime");
            return this;
        }

        public Criteria andNFreeTimeBetween(Long value1, Long value2) {
            addCriterion("N_FREE_TIME between", value1, value2, "nFreeTime");
            return this;
        }

        public Criteria andNFreeTimeNotBetween(Long value1, Long value2) {
            addCriterion("N_FREE_TIME not between", value1, value2, "nFreeTime");
            return this;
        }

        public Criteria andNSubChargeIsNull() {
            addCriterion("N_SUB_CHARGE is null");
            return this;
        }

        public Criteria andNSubChargeIsNotNull() {
            addCriterion("N_SUB_CHARGE is not null");
            return this;
        }

        public Criteria andNSubChargeEqualTo(BigDecimal value) {
            addCriterion("N_SUB_CHARGE =", value, "nSubCharge");
            return this;
        }

        public Criteria andNSubChargeNotEqualTo(BigDecimal value) {
            addCriterion("N_SUB_CHARGE <>", value, "nSubCharge");
            return this;
        }

        public Criteria andNSubChargeGreaterThan(BigDecimal value) {
            addCriterion("N_SUB_CHARGE >", value, "nSubCharge");
            return this;
        }

        public Criteria andNSubChargeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("N_SUB_CHARGE >=", value, "nSubCharge");
            return this;
        }

        public Criteria andNSubChargeLessThan(BigDecimal value) {
            addCriterion("N_SUB_CHARGE <", value, "nSubCharge");
            return this;
        }

        public Criteria andNSubChargeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("N_SUB_CHARGE <=", value, "nSubCharge");
            return this;
        }

        public Criteria andNSubChargeIn(List values) {
            addCriterion("N_SUB_CHARGE in", values, "nSubCharge");
            return this;
        }

        public Criteria andNSubChargeNotIn(List values) {
            addCriterion("N_SUB_CHARGE not in", values, "nSubCharge");
            return this;
        }

        public Criteria andNSubChargeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("N_SUB_CHARGE between", value1, value2, "nSubCharge");
            return this;
        }

        public Criteria andNSubChargeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("N_SUB_CHARGE not between", value1, value2, "nSubCharge");
            return this;
        }

        public Criteria andNTimeSlotLimitIsNull() {
            addCriterion("N_TIME_SLOT_LIMIT is null");
            return this;
        }

        public Criteria andNTimeSlotLimitIsNotNull() {
            addCriterion("N_TIME_SLOT_LIMIT is not null");
            return this;
        }

        public Criteria andNTimeSlotLimitEqualTo(BigDecimal value) {
            addCriterion("N_TIME_SLOT_LIMIT =", value, "nTimeSlotLimit");
            return this;
        }

        public Criteria andNTimeSlotLimitNotEqualTo(BigDecimal value) {
            addCriterion("N_TIME_SLOT_LIMIT <>", value, "nTimeSlotLimit");
            return this;
        }

        public Criteria andNTimeSlotLimitGreaterThan(BigDecimal value) {
            addCriterion("N_TIME_SLOT_LIMIT >", value, "nTimeSlotLimit");
            return this;
        }

        public Criteria andNTimeSlotLimitGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("N_TIME_SLOT_LIMIT >=", value, "nTimeSlotLimit");
            return this;
        }

        public Criteria andNTimeSlotLimitLessThan(BigDecimal value) {
            addCriterion("N_TIME_SLOT_LIMIT <", value, "nTimeSlotLimit");
            return this;
        }

        public Criteria andNTimeSlotLimitLessThanOrEqualTo(BigDecimal value) {
            addCriterion("N_TIME_SLOT_LIMIT <=", value, "nTimeSlotLimit");
            return this;
        }

        public Criteria andNTimeSlotLimitIn(List values) {
            addCriterion("N_TIME_SLOT_LIMIT in", values, "nTimeSlotLimit");
            return this;
        }

        public Criteria andNTimeSlotLimitNotIn(List values) {
            addCriterion("N_TIME_SLOT_LIMIT not in", values, "nTimeSlotLimit");
            return this;
        }

        public Criteria andNTimeSlotLimitBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("N_TIME_SLOT_LIMIT between", value1, value2, "nTimeSlotLimit");
            return this;
        }

        public Criteria andNTimeSlotLimitNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("N_TIME_SLOT_LIMIT not between", value1, value2, "nTimeSlotLimit");
            return this;
        }

        public Criteria andNStartChargeTimeIsNull() {
            addCriterion("N_START_CHARGE_TIME is null");
            return this;
        }

        public Criteria andNStartChargeTimeIsNotNull() {
            addCriterion("N_START_CHARGE_TIME is not null");
            return this;
        }

        public Criteria andNStartChargeTimeEqualTo(Long value) {
            addCriterion("N_START_CHARGE_TIME =", value, "nStartChargeTime");
            return this;
        }

        public Criteria andNStartChargeTimeNotEqualTo(Long value) {
            addCriterion("N_START_CHARGE_TIME <>", value, "nStartChargeTime");
            return this;
        }

        public Criteria andNStartChargeTimeGreaterThan(Long value) {
            addCriterion("N_START_CHARGE_TIME >", value, "nStartChargeTime");
            return this;
        }

        public Criteria andNStartChargeTimeGreaterThanOrEqualTo(Long value) {
            addCriterion("N_START_CHARGE_TIME >=", value, "nStartChargeTime");
            return this;
        }

        public Criteria andNStartChargeTimeLessThan(Long value) {
            addCriterion("N_START_CHARGE_TIME <", value, "nStartChargeTime");
            return this;
        }

        public Criteria andNStartChargeTimeLessThanOrEqualTo(Long value) {
            addCriterion("N_START_CHARGE_TIME <=", value, "nStartChargeTime");
            return this;
        }

        public Criteria andNStartChargeTimeIn(List values) {
            addCriterion("N_START_CHARGE_TIME in", values, "nStartChargeTime");
            return this;
        }

        public Criteria andNStartChargeTimeNotIn(List values) {
            addCriterion("N_START_CHARGE_TIME not in", values, "nStartChargeTime");
            return this;
        }

        public Criteria andNStartChargeTimeBetween(Long value1, Long value2) {
            addCriterion("N_START_CHARGE_TIME between", value1, value2, "nStartChargeTime");
            return this;
        }

        public Criteria andNStartChargeTimeNotBetween(Long value1, Long value2) {
            addCriterion("N_START_CHARGE_TIME not between", value1, value2, "nStartChargeTime");
            return this;
        }

        public Criteria andNStartChargePriceIsNull() {
            addCriterion("N_START_CHARGE_PRICE is null");
            return this;
        }

        public Criteria andNStartChargePriceIsNotNull() {
            addCriterion("N_START_CHARGE_PRICE is not null");
            return this;
        }

        public Criteria andNStartChargePriceEqualTo(BigDecimal value) {
            addCriterion("N_START_CHARGE_PRICE =", value, "nStartChargePrice");
            return this;
        }

        public Criteria andNStartChargePriceNotEqualTo(BigDecimal value) {
            addCriterion("N_START_CHARGE_PRICE <>", value, "nStartChargePrice");
            return this;
        }

        public Criteria andNStartChargePriceGreaterThan(BigDecimal value) {
            addCriterion("N_START_CHARGE_PRICE >", value, "nStartChargePrice");
            return this;
        }

        public Criteria andNStartChargePriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("N_START_CHARGE_PRICE >=", value, "nStartChargePrice");
            return this;
        }

        public Criteria andNStartChargePriceLessThan(BigDecimal value) {
            addCriterion("N_START_CHARGE_PRICE <", value, "nStartChargePrice");
            return this;
        }

        public Criteria andNStartChargePriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("N_START_CHARGE_PRICE <=", value, "nStartChargePrice");
            return this;
        }

        public Criteria andNStartChargePriceIn(List values) {
            addCriterion("N_START_CHARGE_PRICE in", values, "nStartChargePrice");
            return this;
        }

        public Criteria andNStartChargePriceNotIn(List values) {
            addCriterion("N_START_CHARGE_PRICE not in", values, "nStartChargePrice");
            return this;
        }

        public Criteria andNStartChargePriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("N_START_CHARGE_PRICE between", value1, value2, "nStartChargePrice");
            return this;
        }

        public Criteria andNStartChargePriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("N_START_CHARGE_PRICE not between", value1, value2, "nStartChargePrice");
            return this;
        }

        public Criteria andNChargeTimeIsNull() {
            addCriterion("N_CHARGE_TIME is null");
            return this;
        }

        public Criteria andNChargeTimeIsNotNull() {
            addCriterion("N_CHARGE_TIME is not null");
            return this;
        }

        public Criteria andNChargeTimeEqualTo(Long value) {
            addCriterion("N_CHARGE_TIME =", value, "nChargeTime");
            return this;
        }

        public Criteria andNChargeTimeNotEqualTo(Long value) {
            addCriterion("N_CHARGE_TIME <>", value, "nChargeTime");
            return this;
        }

        public Criteria andNChargeTimeGreaterThan(Long value) {
            addCriterion("N_CHARGE_TIME >", value, "nChargeTime");
            return this;
        }

        public Criteria andNChargeTimeGreaterThanOrEqualTo(Long value) {
            addCriterion("N_CHARGE_TIME >=", value, "nChargeTime");
            return this;
        }

        public Criteria andNChargeTimeLessThan(Long value) {
            addCriterion("N_CHARGE_TIME <", value, "nChargeTime");
            return this;
        }

        public Criteria andNChargeTimeLessThanOrEqualTo(Long value) {
            addCriterion("N_CHARGE_TIME <=", value, "nChargeTime");
            return this;
        }

        public Criteria andNChargeTimeIn(List values) {
            addCriterion("N_CHARGE_TIME in", values, "nChargeTime");
            return this;
        }

        public Criteria andNChargeTimeNotIn(List values) {
            addCriterion("N_CHARGE_TIME not in", values, "nChargeTime");
            return this;
        }

        public Criteria andNChargeTimeBetween(Long value1, Long value2) {
            addCriterion("N_CHARGE_TIME between", value1, value2, "nChargeTime");
            return this;
        }

        public Criteria andNChargeTimeNotBetween(Long value1, Long value2) {
            addCriterion("N_CHARGE_TIME not between", value1, value2, "nChargeTime");
            return this;
        }

        public Criteria andNChargePriceIsNull() {
            addCriterion("N_CHARGE_PRICE is null");
            return this;
        }

        public Criteria andNChargePriceIsNotNull() {
            addCriterion("N_CHARGE_PRICE is not null");
            return this;
        }

        public Criteria andNChargePriceEqualTo(BigDecimal value) {
            addCriterion("N_CHARGE_PRICE =", value, "nChargePrice");
            return this;
        }

        public Criteria andNChargePriceNotEqualTo(BigDecimal value) {
            addCriterion("N_CHARGE_PRICE <>", value, "nChargePrice");
            return this;
        }

        public Criteria andNChargePriceGreaterThan(BigDecimal value) {
            addCriterion("N_CHARGE_PRICE >", value, "nChargePrice");
            return this;
        }

        public Criteria andNChargePriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("N_CHARGE_PRICE >=", value, "nChargePrice");
            return this;
        }

        public Criteria andNChargePriceLessThan(BigDecimal value) {
            addCriterion("N_CHARGE_PRICE <", value, "nChargePrice");
            return this;
        }

        public Criteria andNChargePriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("N_CHARGE_PRICE <=", value, "nChargePrice");
            return this;
        }

        public Criteria andNChargePriceIn(List values) {
            addCriterion("N_CHARGE_PRICE in", values, "nChargePrice");
            return this;
        }

        public Criteria andNChargePriceNotIn(List values) {
            addCriterion("N_CHARGE_PRICE not in", values, "nChargePrice");
            return this;
        }

        public Criteria andNChargePriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("N_CHARGE_PRICE between", value1, value2, "nChargePrice");
            return this;
        }

        public Criteria andNChargePriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("N_CHARGE_PRICE not between", value1, value2, "nChargePrice");
            return this;
        }

        public Criteria andNStartHourIsNull() {
            addCriterion("N_START_HOUR is null");
            return this;
        }

        public Criteria andNStartHourIsNotNull() {
            addCriterion("N_START_HOUR is not null");
            return this;
        }

        public Criteria andNStartHourEqualTo(String value) {
            addCriterion("N_START_HOUR =", value, "nStartHour");
            return this;
        }

        public Criteria andNStartHourNotEqualTo(String value) {
            addCriterion("N_START_HOUR <>", value, "nStartHour");
            return this;
        }

        public Criteria andNStartHourGreaterThan(String value) {
            addCriterion("N_START_HOUR >", value, "nStartHour");
            return this;
        }

        public Criteria andNStartHourGreaterThanOrEqualTo(String value) {
            addCriterion("N_START_HOUR >=", value, "nStartHour");
            return this;
        }

        public Criteria andNStartHourLessThan(String value) {
            addCriterion("N_START_HOUR <", value, "nStartHour");
            return this;
        }

        public Criteria andNStartHourLessThanOrEqualTo(String value) {
            addCriterion("N_START_HOUR <=", value, "nStartHour");
            return this;
        }

        public Criteria andNStartHourLike(String value) {
            addCriterion("N_START_HOUR like", value, "nStartHour");
            return this;
        }

        public Criteria andNStartHourNotLike(String value) {
            addCriterion("N_START_HOUR not like", value, "nStartHour");
            return this;
        }

        public Criteria andNStartHourIn(List values) {
            addCriterion("N_START_HOUR in", values, "nStartHour");
            return this;
        }

        public Criteria andNStartHourNotIn(List values) {
            addCriterion("N_START_HOUR not in", values, "nStartHour");
            return this;
        }

        public Criteria andNStartHourBetween(String value1, String value2) {
            addCriterion("N_START_HOUR between", value1, value2, "nStartHour");
            return this;
        }

        public Criteria andNStartHourNotBetween(String value1, String value2) {
            addCriterion("N_START_HOUR not between", value1, value2, "nStartHour");
            return this;
        }

        public Criteria andNEndHourIsNull() {
            addCriterion("N_END_HOUR is null");
            return this;
        }

        public Criteria andNEndHourIsNotNull() {
            addCriterion("N_END_HOUR is not null");
            return this;
        }

        public Criteria andNEndHourEqualTo(String value) {
            addCriterion("N_END_HOUR =", value, "nEndHour");
            return this;
        }

        public Criteria andNEndHourNotEqualTo(String value) {
            addCriterion("N_END_HOUR <>", value, "nEndHour");
            return this;
        }

        public Criteria andNEndHourGreaterThan(String value) {
            addCriterion("N_END_HOUR >", value, "nEndHour");
            return this;
        }

        public Criteria andNEndHourGreaterThanOrEqualTo(String value) {
            addCriterion("N_END_HOUR >=", value, "nEndHour");
            return this;
        }

        public Criteria andNEndHourLessThan(String value) {
            addCriterion("N_END_HOUR <", value, "nEndHour");
            return this;
        }

        public Criteria andNEndHourLessThanOrEqualTo(String value) {
            addCriterion("N_END_HOUR <=", value, "nEndHour");
            return this;
        }

        public Criteria andNEndHourLike(String value) {
            addCriterion("N_END_HOUR like", value, "nEndHour");
            return this;
        }

        public Criteria andNEndHourNotLike(String value) {
            addCriterion("N_END_HOUR not like", value, "nEndHour");
            return this;
        }

        public Criteria andNEndHourIn(List values) {
            addCriterion("N_END_HOUR in", values, "nEndHour");
            return this;
        }

        public Criteria andNEndHourNotIn(List values) {
            addCriterion("N_END_HOUR not in", values, "nEndHour");
            return this;
        }

        public Criteria andNEndHourBetween(String value1, String value2) {
            addCriterion("N_END_HOUR between", value1, value2, "nEndHour");
            return this;
        }

        public Criteria andNEndHourNotBetween(String value1, String value2) {
            addCriterion("N_END_HOUR not between", value1, value2, "nEndHour");
            return this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("TYPE is null");
            return this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("TYPE is not null");
            return this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("TYPE =", value, "type");
            return this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("TYPE <>", value, "type");
            return this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("TYPE >", value, "type");
            return this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("TYPE >=", value, "type");
            return this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("TYPE <", value, "type");
            return this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("TYPE <=", value, "type");
            return this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("TYPE like", value, "type");
            return this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("TYPE not like", value, "type");
            return this;
        }

        public Criteria andTypeIn(List values) {
            addCriterion("TYPE in", values, "type");
            return this;
        }

        public Criteria andTypeNotIn(List values) {
            addCriterion("TYPE not in", values, "type");
            return this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("TYPE between", value1, value2, "type");
            return this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("TYPE not between", value1, value2, "type");
            return this;
        }
    }
}