package com.compass.park.model;

public class ParkBeanExample extends ParkBean {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public static final int EXAMPLE_IGNORE = 0;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public static final int EXAMPLE_NULL = 1;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public static final int EXAMPLE_NOT_NULL = 2;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public static final int EXAMPLE_EQUALS = 3;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public static final int EXAMPLE_NOT_EQUALS = 4;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public static final int EXAMPLE_GREATER_THAN = 5;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public static final int EXAMPLE_GREATER_THAN_OR_EQUAL = 6;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public static final int EXAMPLE_LESS_THAN = 7;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public static final int EXAMPLE_LESS_THAN_OR_EQUAL = 8;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public static final int EXAMPLE_LIKE = 9;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    private boolean combineTypeOr;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    private int outParkingId_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    private int merchantName_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    private int merchantServicePhone_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    private int accountNo_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    private int cityId_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    private int equipmentName_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    private int parkingAddress_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    private int longitude_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    private int latitude_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    private int parkingStartTime_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    private int parkingEndTime_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    private int parkingNumber_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    private int parkingLotType_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    private int parkingType_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    private int paymentMode_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    private int payType_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    private int shopingmallId_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    private int parkingFeeDescription_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    private int contactName_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    private int contactMobile_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    private int contactTel_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    private int contactEmali_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    private int contactWeixin_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    private int contactAlipay_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    private int parkingName_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    private int timeOut_Indicator;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public void setCombineTypeOr(boolean combineTypeOr) {
        this.combineTypeOr = combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public boolean isCombineTypeOr() {
        return combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public int getOutParkingId_Indicator() {
        return outParkingId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public void setOutParkingId_Indicator(int outParkingId_Indicator) {
        this.outParkingId_Indicator = outParkingId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public int getMerchantName_Indicator() {
        return merchantName_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public void setMerchantName_Indicator(int merchantName_Indicator) {
        this.merchantName_Indicator = merchantName_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public int getMerchantServicePhone_Indicator() {
        return merchantServicePhone_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public void setMerchantServicePhone_Indicator(int merchantServicePhone_Indicator) {
        this.merchantServicePhone_Indicator = merchantServicePhone_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public int getAccountNo_Indicator() {
        return accountNo_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public void setAccountNo_Indicator(int accountNo_Indicator) {
        this.accountNo_Indicator = accountNo_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public int getCityId_Indicator() {
        return cityId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public void setCityId_Indicator(int cityId_Indicator) {
        this.cityId_Indicator = cityId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public int getEquipmentName_Indicator() {
        return equipmentName_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public void setEquipmentName_Indicator(int equipmentName_Indicator) {
        this.equipmentName_Indicator = equipmentName_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public int getParkingAddress_Indicator() {
        return parkingAddress_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public void setParkingAddress_Indicator(int parkingAddress_Indicator) {
        this.parkingAddress_Indicator = parkingAddress_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public int getLongitude_Indicator() {
        return longitude_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public void setLongitude_Indicator(int longitude_Indicator) {
        this.longitude_Indicator = longitude_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public int getLatitude_Indicator() {
        return latitude_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public void setLatitude_Indicator(int latitude_Indicator) {
        this.latitude_Indicator = latitude_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public int getParkingStartTime_Indicator() {
        return parkingStartTime_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public void setParkingStartTime_Indicator(int parkingStartTime_Indicator) {
        this.parkingStartTime_Indicator = parkingStartTime_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public int getParkingEndTime_Indicator() {
        return parkingEndTime_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public void setParkingEndTime_Indicator(int parkingEndTime_Indicator) {
        this.parkingEndTime_Indicator = parkingEndTime_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public int getParkingNumber_Indicator() {
        return parkingNumber_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public void setParkingNumber_Indicator(int parkingNumber_Indicator) {
        this.parkingNumber_Indicator = parkingNumber_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public int getParkingLotType_Indicator() {
        return parkingLotType_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public void setParkingLotType_Indicator(int parkingLotType_Indicator) {
        this.parkingLotType_Indicator = parkingLotType_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public int getParkingType_Indicator() {
        return parkingType_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public void setParkingType_Indicator(int parkingType_Indicator) {
        this.parkingType_Indicator = parkingType_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public int getPaymentMode_Indicator() {
        return paymentMode_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public void setPaymentMode_Indicator(int paymentMode_Indicator) {
        this.paymentMode_Indicator = paymentMode_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public int getPayType_Indicator() {
        return payType_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public void setPayType_Indicator(int payType_Indicator) {
        this.payType_Indicator = payType_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public int getShopingmallId_Indicator() {
        return shopingmallId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public void setShopingmallId_Indicator(int shopingmallId_Indicator) {
        this.shopingmallId_Indicator = shopingmallId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public int getParkingFeeDescription_Indicator() {
        return parkingFeeDescription_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public void setParkingFeeDescription_Indicator(int parkingFeeDescription_Indicator) {
        this.parkingFeeDescription_Indicator = parkingFeeDescription_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public int getContactName_Indicator() {
        return contactName_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public void setContactName_Indicator(int contactName_Indicator) {
        this.contactName_Indicator = contactName_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public int getContactMobile_Indicator() {
        return contactMobile_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public void setContactMobile_Indicator(int contactMobile_Indicator) {
        this.contactMobile_Indicator = contactMobile_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public int getContactTel_Indicator() {
        return contactTel_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public void setContactTel_Indicator(int contactTel_Indicator) {
        this.contactTel_Indicator = contactTel_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public int getContactEmali_Indicator() {
        return contactEmali_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public void setContactEmali_Indicator(int contactEmali_Indicator) {
        this.contactEmali_Indicator = contactEmali_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public int getContactWeixin_Indicator() {
        return contactWeixin_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public void setContactWeixin_Indicator(int contactWeixin_Indicator) {
        this.contactWeixin_Indicator = contactWeixin_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public int getContactAlipay_Indicator() {
        return contactAlipay_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public void setContactAlipay_Indicator(int contactAlipay_Indicator) {
        this.contactAlipay_Indicator = contactAlipay_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public int getParkingName_Indicator() {
        return parkingName_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public void setParkingName_Indicator(int parkingName_Indicator) {
        this.parkingName_Indicator = parkingName_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public int getTimeOut_Indicator() {
        return timeOut_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_PARK
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public void setTimeOut_Indicator(int timeOut_Indicator) {
        this.timeOut_Indicator = timeOut_Indicator;
    }
}