package com.compass.park.model;

import java.util.Date;

public class ParkBean {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TB_PARK.OUT_PARKING_ID
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    private String outParkingId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TB_PARK.MERCHANT_NAME
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    private String merchantName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TB_PARK.MERCHANT_SERVICE_PHONE
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    private String merchantServicePhone;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TB_PARK.ACCOUNT_NO
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    private String accountNo;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TB_PARK.CITY_ID
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    private String cityId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TB_PARK.EQUIPMENT_NAME
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    private String equipmentName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TB_PARK.PARKING_ADDRESS
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    private String parkingAddress;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TB_PARK.LONGITUDE
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    private String longitude;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TB_PARK.LATITUDE
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    private String latitude;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TB_PARK.PARKING_START_TIME
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    private String parkingStartTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TB_PARK.PARKING_END_TIME
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    private String parkingEndTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TB_PARK.PARKING_NUMBER
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    private String parkingNumber;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TB_PARK.PARKING_LOT_TYPE
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    private String parkingLotType;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TB_PARK.PARKING_TYPE
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    private String parkingType;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TB_PARK.PAYMENT_MODE
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    private String paymentMode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TB_PARK.PAY_TYPE
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    private String payType;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TB_PARK.SHOPINGMALL_ID
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    private String shopingmallId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TB_PARK.PARKING_FEE_DESCRIPTION
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    private String parkingFeeDescription;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TB_PARK.CONTACT_NAME
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    private String contactName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TB_PARK.CONTACT_MOBILE
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    private String contactMobile;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TB_PARK.CONTACT_TEL
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    private String contactTel;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TB_PARK.CONTACT_EMALI
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    private String contactEmali;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TB_PARK.CONTACT_WEIXIN
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    private String contactWeixin;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TB_PARK.CONTACT_ALIPAY
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    private String contactAlipay;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TB_PARK.PARKING_NAME
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    private String parkingName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TB_PARK.TIME_OUT
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    private String timeOut;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TB_PARK.OUT_PARKING_ID
     *
     * @return the value of TB_PARK.OUT_PARKING_ID
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public String getOutParkingId() {
        return outParkingId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TB_PARK.OUT_PARKING_ID
     *
     * @param outParkingId the value for TB_PARK.OUT_PARKING_ID
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public void setOutParkingId(String outParkingId) {
        this.outParkingId = outParkingId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TB_PARK.MERCHANT_NAME
     *
     * @return the value of TB_PARK.MERCHANT_NAME
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public String getMerchantName() {
        return merchantName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TB_PARK.MERCHANT_NAME
     *
     * @param merchantName the value for TB_PARK.MERCHANT_NAME
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public void setMerchantName(String merchantName) {
        this.merchantName = merchantName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TB_PARK.MERCHANT_SERVICE_PHONE
     *
     * @return the value of TB_PARK.MERCHANT_SERVICE_PHONE
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public String getMerchantServicePhone() {
        return merchantServicePhone;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TB_PARK.MERCHANT_SERVICE_PHONE
     *
     * @param merchantServicePhone the value for TB_PARK.MERCHANT_SERVICE_PHONE
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public void setMerchantServicePhone(String merchantServicePhone) {
        this.merchantServicePhone = merchantServicePhone;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TB_PARK.ACCOUNT_NO
     *
     * @return the value of TB_PARK.ACCOUNT_NO
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public String getAccountNo() {
        return accountNo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TB_PARK.ACCOUNT_NO
     *
     * @param accountNo the value for TB_PARK.ACCOUNT_NO
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public void setAccountNo(String accountNo) {
        this.accountNo = accountNo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TB_PARK.CITY_ID
     *
     * @return the value of TB_PARK.CITY_ID
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public String getCityId() {
        return cityId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TB_PARK.CITY_ID
     *
     * @param cityId the value for TB_PARK.CITY_ID
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public void setCityId(String cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TB_PARK.EQUIPMENT_NAME
     *
     * @return the value of TB_PARK.EQUIPMENT_NAME
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public String getEquipmentName() {
        return equipmentName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TB_PARK.EQUIPMENT_NAME
     *
     * @param equipmentName the value for TB_PARK.EQUIPMENT_NAME
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public void setEquipmentName(String equipmentName) {
        this.equipmentName = equipmentName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TB_PARK.PARKING_ADDRESS
     *
     * @return the value of TB_PARK.PARKING_ADDRESS
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public String getParkingAddress() {
        return parkingAddress;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TB_PARK.PARKING_ADDRESS
     *
     * @param parkingAddress the value for TB_PARK.PARKING_ADDRESS
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public void setParkingAddress(String parkingAddress) {
        this.parkingAddress = parkingAddress;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TB_PARK.LONGITUDE
     *
     * @return the value of TB_PARK.LONGITUDE
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TB_PARK.LONGITUDE
     *
     * @param longitude the value for TB_PARK.LONGITUDE
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TB_PARK.LATITUDE
     *
     * @return the value of TB_PARK.LATITUDE
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TB_PARK.LATITUDE
     *
     * @param latitude the value for TB_PARK.LATITUDE
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TB_PARK.PARKING_START_TIME
     *
     * @return the value of TB_PARK.PARKING_START_TIME
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public String getParkingStartTime() {
        return parkingStartTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TB_PARK.PARKING_START_TIME
     *
     * @param parkingStartTime the value for TB_PARK.PARKING_START_TIME
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public void setParkingStartTime(String parkingStartTime) {
        this.parkingStartTime = parkingStartTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TB_PARK.PARKING_END_TIME
     *
     * @return the value of TB_PARK.PARKING_END_TIME
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public String getParkingEndTime() {
        return parkingEndTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TB_PARK.PARKING_END_TIME
     *
     * @param parkingEndTime the value for TB_PARK.PARKING_END_TIME
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public void setParkingEndTime(String parkingEndTime) {
        this.parkingEndTime = parkingEndTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TB_PARK.PARKING_NUMBER
     *
     * @return the value of TB_PARK.PARKING_NUMBER
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public String getParkingNumber() {
        return parkingNumber;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TB_PARK.PARKING_NUMBER
     *
     * @param parkingNumber the value for TB_PARK.PARKING_NUMBER
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public void setParkingNumber(String parkingNumber) {
        this.parkingNumber = parkingNumber;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TB_PARK.PARKING_LOT_TYPE
     *
     * @return the value of TB_PARK.PARKING_LOT_TYPE
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public String getParkingLotType() {
        return parkingLotType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TB_PARK.PARKING_LOT_TYPE
     *
     * @param parkingLotType the value for TB_PARK.PARKING_LOT_TYPE
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public void setParkingLotType(String parkingLotType) {
        this.parkingLotType = parkingLotType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TB_PARK.PARKING_TYPE
     *
     * @return the value of TB_PARK.PARKING_TYPE
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public String getParkingType() {
        return parkingType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TB_PARK.PARKING_TYPE
     *
     * @param parkingType the value for TB_PARK.PARKING_TYPE
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public void setParkingType(String parkingType) {
        this.parkingType = parkingType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TB_PARK.PAYMENT_MODE
     *
     * @return the value of TB_PARK.PAYMENT_MODE
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public String getPaymentMode() {
        return paymentMode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TB_PARK.PAYMENT_MODE
     *
     * @param paymentMode the value for TB_PARK.PAYMENT_MODE
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public void setPaymentMode(String paymentMode) {
        this.paymentMode = paymentMode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TB_PARK.PAY_TYPE
     *
     * @return the value of TB_PARK.PAY_TYPE
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public String getPayType() {
        return payType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TB_PARK.PAY_TYPE
     *
     * @param payType the value for TB_PARK.PAY_TYPE
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public void setPayType(String payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TB_PARK.SHOPINGMALL_ID
     *
     * @return the value of TB_PARK.SHOPINGMALL_ID
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public String getShopingmallId() {
        return shopingmallId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TB_PARK.SHOPINGMALL_ID
     *
     * @param shopingmallId the value for TB_PARK.SHOPINGMALL_ID
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public void setShopingmallId(String shopingmallId) {
        this.shopingmallId = shopingmallId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TB_PARK.PARKING_FEE_DESCRIPTION
     *
     * @return the value of TB_PARK.PARKING_FEE_DESCRIPTION
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public String getParkingFeeDescription() {
        return parkingFeeDescription;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TB_PARK.PARKING_FEE_DESCRIPTION
     *
     * @param parkingFeeDescription the value for TB_PARK.PARKING_FEE_DESCRIPTION
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public void setParkingFeeDescription(String parkingFeeDescription) {
        this.parkingFeeDescription = parkingFeeDescription;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TB_PARK.CONTACT_NAME
     *
     * @return the value of TB_PARK.CONTACT_NAME
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public String getContactName() {
        return contactName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TB_PARK.CONTACT_NAME
     *
     * @param contactName the value for TB_PARK.CONTACT_NAME
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public void setContactName(String contactName) {
        this.contactName = contactName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TB_PARK.CONTACT_MOBILE
     *
     * @return the value of TB_PARK.CONTACT_MOBILE
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public String getContactMobile() {
        return contactMobile;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TB_PARK.CONTACT_MOBILE
     *
     * @param contactMobile the value for TB_PARK.CONTACT_MOBILE
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public void setContactMobile(String contactMobile) {
        this.contactMobile = contactMobile;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TB_PARK.CONTACT_TEL
     *
     * @return the value of TB_PARK.CONTACT_TEL
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public String getContactTel() {
        return contactTel;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TB_PARK.CONTACT_TEL
     *
     * @param contactTel the value for TB_PARK.CONTACT_TEL
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public void setContactTel(String contactTel) {
        this.contactTel = contactTel;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TB_PARK.CONTACT_EMALI
     *
     * @return the value of TB_PARK.CONTACT_EMALI
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public String getContactEmali() {
        return contactEmali;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TB_PARK.CONTACT_EMALI
     *
     * @param contactEmali the value for TB_PARK.CONTACT_EMALI
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public void setContactEmali(String contactEmali) {
        this.contactEmali = contactEmali;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TB_PARK.CONTACT_WEIXIN
     *
     * @return the value of TB_PARK.CONTACT_WEIXIN
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public String getContactWeixin() {
        return contactWeixin;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TB_PARK.CONTACT_WEIXIN
     *
     * @param contactWeixin the value for TB_PARK.CONTACT_WEIXIN
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public void setContactWeixin(String contactWeixin) {
        this.contactWeixin = contactWeixin;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TB_PARK.CONTACT_ALIPAY
     *
     * @return the value of TB_PARK.CONTACT_ALIPAY
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public String getContactAlipay() {
        return contactAlipay;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TB_PARK.CONTACT_ALIPAY
     *
     * @param contactAlipay the value for TB_PARK.CONTACT_ALIPAY
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public void setContactAlipay(String contactAlipay) {
        this.contactAlipay = contactAlipay;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TB_PARK.PARKING_NAME
     *
     * @return the value of TB_PARK.PARKING_NAME
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public String getParkingName() {
        return parkingName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TB_PARK.PARKING_NAME
     *
     * @param parkingName the value for TB_PARK.PARKING_NAME
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public void setParkingName(String parkingName) {
        this.parkingName = parkingName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TB_PARK.TIME_OUT
     *
     * @return the value of TB_PARK.TIME_OUT
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public String getTimeOut() {
        return timeOut;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TB_PARK.TIME_OUT
     *
     * @param timeOut the value for TB_PARK.TIME_OUT
     *
     * @abatorgenerated Sun Oct 29 11:25:55 CST 2017
     */
    public void setTimeOut(String timeOut) {
        this.timeOut = timeOut;
    }
    
    private Integer start;
	private Integer end;
	private String createUserId;
	private String modifyUserId;
	private Date createDatetime;
	private Date modifyDatetime;
	private String status;//0不可用，1 可用
	private String isSubPark; //是否查询子停车场 1：查询
	private Integer licenseCount;
	
	public Integer getStart() {
		return start;
	}

	public void setStart(Integer start) {
		this.start = start;
	}

	public Integer getEnd() {
		return end;
	}

	public void setEnd(Integer end) {
		this.end = end;
	}

	public String getCreateUserId() {
		return createUserId;
	}

	public void setCreateUserId(String createUserId) {
		this.createUserId = createUserId;
	}

	public String getModifyUserId() {
		return modifyUserId;
	}

	public void setModifyUserId(String modifyUserId) {
		this.modifyUserId = modifyUserId;
	}

	public Date getCreateDatetime() {
		return createDatetime;
	}

	public void setCreateDatetime(Date createDatetime) {
		this.createDatetime = createDatetime;
	}

	public Date getModifyDatetime() {
		return modifyDatetime;
	}

	public void setModifyDatetime(Date modifyDatetime) {
		this.modifyDatetime = modifyDatetime;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getIsSubPark() {
		return isSubPark;
	}

	public void setIsSubPark(String isSubPark) {
		this.isSubPark = isSubPark;
	}

	public Integer getLicenseCount() {
		return licenseCount;
	}

	public void setLicenseCount(Integer licenseCount) {
		this.licenseCount = licenseCount;
	}
}