package com.compass.order.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class OrderPayBeanExample {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table TB_ORDER_PAY
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table TB_ORDER_PAY
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    protected List oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TB_ORDER_PAY
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    public OrderPayBeanExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TB_ORDER_PAY
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    protected OrderPayBeanExample(OrderPayBeanExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TB_ORDER_PAY
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TB_ORDER_PAY
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TB_ORDER_PAY
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TB_ORDER_PAY
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TB_ORDER_PAY
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TB_ORDER_PAY
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TB_ORDER_PAY
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table TB_ORDER_PAY
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andOrderIdIsNull() {
            addCriterion("ORDER_ID is null");
            return this;
        }

        public Criteria andOrderIdIsNotNull() {
            addCriterion("ORDER_ID is not null");
            return this;
        }

        public Criteria andOrderIdEqualTo(String value) {
            addCriterion("ORDER_ID =", value, "orderId");
            return this;
        }

        public Criteria andOrderIdNotEqualTo(String value) {
            addCriterion("ORDER_ID <>", value, "orderId");
            return this;
        }

        public Criteria andOrderIdGreaterThan(String value) {
            addCriterion("ORDER_ID >", value, "orderId");
            return this;
        }

        public Criteria andOrderIdGreaterThanOrEqualTo(String value) {
            addCriterion("ORDER_ID >=", value, "orderId");
            return this;
        }

        public Criteria andOrderIdLessThan(String value) {
            addCriterion("ORDER_ID <", value, "orderId");
            return this;
        }

        public Criteria andOrderIdLessThanOrEqualTo(String value) {
            addCriterion("ORDER_ID <=", value, "orderId");
            return this;
        }

        public Criteria andOrderIdLike(String value) {
            addCriterion("ORDER_ID like", value, "orderId");
            return this;
        }

        public Criteria andOrderIdNotLike(String value) {
            addCriterion("ORDER_ID not like", value, "orderId");
            return this;
        }

        public Criteria andOrderIdIn(List values) {
            addCriterion("ORDER_ID in", values, "orderId");
            return this;
        }

        public Criteria andOrderIdNotIn(List values) {
            addCriterion("ORDER_ID not in", values, "orderId");
            return this;
        }

        public Criteria andOrderIdBetween(String value1, String value2) {
            addCriterion("ORDER_ID between", value1, value2, "orderId");
            return this;
        }

        public Criteria andOrderIdNotBetween(String value1, String value2) {
            addCriterion("ORDER_ID not between", value1, value2, "orderId");
            return this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("USER_ID is null");
            return this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("USER_ID is not null");
            return this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("USER_ID =", value, "userId");
            return this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("USER_ID <>", value, "userId");
            return this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("USER_ID >", value, "userId");
            return this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("USER_ID >=", value, "userId");
            return this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("USER_ID <", value, "userId");
            return this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("USER_ID <=", value, "userId");
            return this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("USER_ID like", value, "userId");
            return this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("USER_ID not like", value, "userId");
            return this;
        }

        public Criteria andUserIdIn(List values) {
            addCriterion("USER_ID in", values, "userId");
            return this;
        }

        public Criteria andUserIdNotIn(List values) {
            addCriterion("USER_ID not in", values, "userId");
            return this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("USER_ID between", value1, value2, "userId");
            return this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("USER_ID not between", value1, value2, "userId");
            return this;
        }

        public Criteria andOutParkingIdIsNull() {
            addCriterion("OUT_PARKING_ID is null");
            return this;
        }

        public Criteria andOutParkingIdIsNotNull() {
            addCriterion("OUT_PARKING_ID is not null");
            return this;
        }

        public Criteria andOutParkingIdEqualTo(String value) {
            addCriterion("OUT_PARKING_ID =", value, "outParkingId");
            return this;
        }

        public Criteria andOutParkingIdNotEqualTo(String value) {
            addCriterion("OUT_PARKING_ID <>", value, "outParkingId");
            return this;
        }

        public Criteria andOutParkingIdGreaterThan(String value) {
            addCriterion("OUT_PARKING_ID >", value, "outParkingId");
            return this;
        }

        public Criteria andOutParkingIdGreaterThanOrEqualTo(String value) {
            addCriterion("OUT_PARKING_ID >=", value, "outParkingId");
            return this;
        }

        public Criteria andOutParkingIdLessThan(String value) {
            addCriterion("OUT_PARKING_ID <", value, "outParkingId");
            return this;
        }

        public Criteria andOutParkingIdLessThanOrEqualTo(String value) {
            addCriterion("OUT_PARKING_ID <=", value, "outParkingId");
            return this;
        }

        public Criteria andOutParkingIdLike(String value) {
            addCriterion("OUT_PARKING_ID like", value, "outParkingId");
            return this;
        }

        public Criteria andOutParkingIdNotLike(String value) {
            addCriterion("OUT_PARKING_ID not like", value, "outParkingId");
            return this;
        }

        public Criteria andOutParkingIdIn(List values) {
            addCriterion("OUT_PARKING_ID in", values, "outParkingId");
            return this;
        }

        public Criteria andOutParkingIdNotIn(List values) {
            addCriterion("OUT_PARKING_ID not in", values, "outParkingId");
            return this;
        }

        public Criteria andOutParkingIdBetween(String value1, String value2) {
            addCriterion("OUT_PARKING_ID between", value1, value2, "outParkingId");
            return this;
        }

        public Criteria andOutParkingIdNotBetween(String value1, String value2) {
            addCriterion("OUT_PARKING_ID not between", value1, value2, "outParkingId");
            return this;
        }

        public Criteria andParkingNameIsNull() {
            addCriterion("PARKING_NAME is null");
            return this;
        }

        public Criteria andParkingNameIsNotNull() {
            addCriterion("PARKING_NAME is not null");
            return this;
        }

        public Criteria andParkingNameEqualTo(String value) {
            addCriterion("PARKING_NAME =", value, "parkingName");
            return this;
        }

        public Criteria andParkingNameNotEqualTo(String value) {
            addCriterion("PARKING_NAME <>", value, "parkingName");
            return this;
        }

        public Criteria andParkingNameGreaterThan(String value) {
            addCriterion("PARKING_NAME >", value, "parkingName");
            return this;
        }

        public Criteria andParkingNameGreaterThanOrEqualTo(String value) {
            addCriterion("PARKING_NAME >=", value, "parkingName");
            return this;
        }

        public Criteria andParkingNameLessThan(String value) {
            addCriterion("PARKING_NAME <", value, "parkingName");
            return this;
        }

        public Criteria andParkingNameLessThanOrEqualTo(String value) {
            addCriterion("PARKING_NAME <=", value, "parkingName");
            return this;
        }

        public Criteria andParkingNameLike(String value) {
            addCriterion("PARKING_NAME like", value, "parkingName");
            return this;
        }

        public Criteria andParkingNameNotLike(String value) {
            addCriterion("PARKING_NAME not like", value, "parkingName");
            return this;
        }

        public Criteria andParkingNameIn(List values) {
            addCriterion("PARKING_NAME in", values, "parkingName");
            return this;
        }

        public Criteria andParkingNameNotIn(List values) {
            addCriterion("PARKING_NAME not in", values, "parkingName");
            return this;
        }

        public Criteria andParkingNameBetween(String value1, String value2) {
            addCriterion("PARKING_NAME between", value1, value2, "parkingName");
            return this;
        }

        public Criteria andParkingNameNotBetween(String value1, String value2) {
            addCriterion("PARKING_NAME not between", value1, value2, "parkingName");
            return this;
        }

        public Criteria andCarNumberIsNull() {
            addCriterion("CAR_NUMBER is null");
            return this;
        }

        public Criteria andCarNumberIsNotNull() {
            addCriterion("CAR_NUMBER is not null");
            return this;
        }

        public Criteria andCarNumberEqualTo(String value) {
            addCriterion("CAR_NUMBER =", value, "carNumber");
            return this;
        }

        public Criteria andCarNumberNotEqualTo(String value) {
            addCriterion("CAR_NUMBER <>", value, "carNumber");
            return this;
        }

        public Criteria andCarNumberGreaterThan(String value) {
            addCriterion("CAR_NUMBER >", value, "carNumber");
            return this;
        }

        public Criteria andCarNumberGreaterThanOrEqualTo(String value) {
            addCriterion("CAR_NUMBER >=", value, "carNumber");
            return this;
        }

        public Criteria andCarNumberLessThan(String value) {
            addCriterion("CAR_NUMBER <", value, "carNumber");
            return this;
        }

        public Criteria andCarNumberLessThanOrEqualTo(String value) {
            addCriterion("CAR_NUMBER <=", value, "carNumber");
            return this;
        }

        public Criteria andCarNumberLike(String value) {
            addCriterion("CAR_NUMBER like", value, "carNumber");
            return this;
        }

        public Criteria andCarNumberNotLike(String value) {
            addCriterion("CAR_NUMBER not like", value, "carNumber");
            return this;
        }

        public Criteria andCarNumberIn(List values) {
            addCriterion("CAR_NUMBER in", values, "carNumber");
            return this;
        }

        public Criteria andCarNumberNotIn(List values) {
            addCriterion("CAR_NUMBER not in", values, "carNumber");
            return this;
        }

        public Criteria andCarNumberBetween(String value1, String value2) {
            addCriterion("CAR_NUMBER between", value1, value2, "carNumber");
            return this;
        }

        public Criteria andCarNumberNotBetween(String value1, String value2) {
            addCriterion("CAR_NUMBER not between", value1, value2, "carNumber");
            return this;
        }

        public Criteria andOutOrderNoIsNull() {
            addCriterion("OUT_ORDER_NO is null");
            return this;
        }

        public Criteria andOutOrderNoIsNotNull() {
            addCriterion("OUT_ORDER_NO is not null");
            return this;
        }

        public Criteria andOutOrderNoEqualTo(String value) {
            addCriterion("OUT_ORDER_NO =", value, "outOrderNo");
            return this;
        }

        public Criteria andOutOrderNoNotEqualTo(String value) {
            addCriterion("OUT_ORDER_NO <>", value, "outOrderNo");
            return this;
        }

        public Criteria andOutOrderNoGreaterThan(String value) {
            addCriterion("OUT_ORDER_NO >", value, "outOrderNo");
            return this;
        }

        public Criteria andOutOrderNoGreaterThanOrEqualTo(String value) {
            addCriterion("OUT_ORDER_NO >=", value, "outOrderNo");
            return this;
        }

        public Criteria andOutOrderNoLessThan(String value) {
            addCriterion("OUT_ORDER_NO <", value, "outOrderNo");
            return this;
        }

        public Criteria andOutOrderNoLessThanOrEqualTo(String value) {
            addCriterion("OUT_ORDER_NO <=", value, "outOrderNo");
            return this;
        }

        public Criteria andOutOrderNoLike(String value) {
            addCriterion("OUT_ORDER_NO like", value, "outOrderNo");
            return this;
        }

        public Criteria andOutOrderNoNotLike(String value) {
            addCriterion("OUT_ORDER_NO not like", value, "outOrderNo");
            return this;
        }

        public Criteria andOutOrderNoIn(List values) {
            addCriterion("OUT_ORDER_NO in", values, "outOrderNo");
            return this;
        }

        public Criteria andOutOrderNoNotIn(List values) {
            addCriterion("OUT_ORDER_NO not in", values, "outOrderNo");
            return this;
        }

        public Criteria andOutOrderNoBetween(String value1, String value2) {
            addCriterion("OUT_ORDER_NO between", value1, value2, "outOrderNo");
            return this;
        }

        public Criteria andOutOrderNoNotBetween(String value1, String value2) {
            addCriterion("OUT_ORDER_NO not between", value1, value2, "outOrderNo");
            return this;
        }

        public Criteria andOrderStatusIsNull() {
            addCriterion("ORDER_STATUS is null");
            return this;
        }

        public Criteria andOrderStatusIsNotNull() {
            addCriterion("ORDER_STATUS is not null");
            return this;
        }

        public Criteria andOrderStatusEqualTo(String value) {
            addCriterion("ORDER_STATUS =", value, "orderStatus");
            return this;
        }

        public Criteria andOrderStatusNotEqualTo(String value) {
            addCriterion("ORDER_STATUS <>", value, "orderStatus");
            return this;
        }

        public Criteria andOrderStatusGreaterThan(String value) {
            addCriterion("ORDER_STATUS >", value, "orderStatus");
            return this;
        }

        public Criteria andOrderStatusGreaterThanOrEqualTo(String value) {
            addCriterion("ORDER_STATUS >=", value, "orderStatus");
            return this;
        }

        public Criteria andOrderStatusLessThan(String value) {
            addCriterion("ORDER_STATUS <", value, "orderStatus");
            return this;
        }

        public Criteria andOrderStatusLessThanOrEqualTo(String value) {
            addCriterion("ORDER_STATUS <=", value, "orderStatus");
            return this;
        }

        public Criteria andOrderStatusLike(String value) {
            addCriterion("ORDER_STATUS like", value, "orderStatus");
            return this;
        }

        public Criteria andOrderStatusNotLike(String value) {
            addCriterion("ORDER_STATUS not like", value, "orderStatus");
            return this;
        }

        public Criteria andOrderStatusIn(List values) {
            addCriterion("ORDER_STATUS in", values, "orderStatus");
            return this;
        }

        public Criteria andOrderStatusNotIn(List values) {
            addCriterion("ORDER_STATUS not in", values, "orderStatus");
            return this;
        }

        public Criteria andOrderStatusBetween(String value1, String value2) {
            addCriterion("ORDER_STATUS between", value1, value2, "orderStatus");
            return this;
        }

        public Criteria andOrderStatusNotBetween(String value1, String value2) {
            addCriterion("ORDER_STATUS not between", value1, value2, "orderStatus");
            return this;
        }

        public Criteria andOrderTimeIsNull() {
            addCriterion("ORDER_TIME is null");
            return this;
        }

        public Criteria andOrderTimeIsNotNull() {
            addCriterion("ORDER_TIME is not null");
            return this;
        }

        public Criteria andOrderTimeEqualTo(String value) {
            addCriterion("ORDER_TIME =", value, "orderTime");
            return this;
        }

        public Criteria andOrderTimeNotEqualTo(String value) {
            addCriterion("ORDER_TIME <>", value, "orderTime");
            return this;
        }

        public Criteria andOrderTimeGreaterThan(String value) {
            addCriterion("ORDER_TIME >", value, "orderTime");
            return this;
        }

        public Criteria andOrderTimeGreaterThanOrEqualTo(String value) {
            addCriterion("ORDER_TIME >=", value, "orderTime");
            return this;
        }

        public Criteria andOrderTimeLessThan(String value) {
            addCriterion("ORDER_TIME <", value, "orderTime");
            return this;
        }

        public Criteria andOrderTimeLessThanOrEqualTo(String value) {
            addCriterion("ORDER_TIME <=", value, "orderTime");
            return this;
        }

        public Criteria andOrderTimeLike(String value) {
            addCriterion("ORDER_TIME like", value, "orderTime");
            return this;
        }

        public Criteria andOrderTimeNotLike(String value) {
            addCriterion("ORDER_TIME not like", value, "orderTime");
            return this;
        }

        public Criteria andOrderTimeIn(List values) {
            addCriterion("ORDER_TIME in", values, "orderTime");
            return this;
        }

        public Criteria andOrderTimeNotIn(List values) {
            addCriterion("ORDER_TIME not in", values, "orderTime");
            return this;
        }

        public Criteria andOrderTimeBetween(String value1, String value2) {
            addCriterion("ORDER_TIME between", value1, value2, "orderTime");
            return this;
        }

        public Criteria andOrderTimeNotBetween(String value1, String value2) {
            addCriterion("ORDER_TIME not between", value1, value2, "orderTime");
            return this;
        }

        public Criteria andOrderNoIsNull() {
            addCriterion("ORDER_NO is null");
            return this;
        }

        public Criteria andOrderNoIsNotNull() {
            addCriterion("ORDER_NO is not null");
            return this;
        }

        public Criteria andOrderNoEqualTo(String value) {
            addCriterion("ORDER_NO =", value, "orderNo");
            return this;
        }

        public Criteria andOrderNoNotEqualTo(String value) {
            addCriterion("ORDER_NO <>", value, "orderNo");
            return this;
        }

        public Criteria andOrderNoGreaterThan(String value) {
            addCriterion("ORDER_NO >", value, "orderNo");
            return this;
        }

        public Criteria andOrderNoGreaterThanOrEqualTo(String value) {
            addCriterion("ORDER_NO >=", value, "orderNo");
            return this;
        }

        public Criteria andOrderNoLessThan(String value) {
            addCriterion("ORDER_NO <", value, "orderNo");
            return this;
        }

        public Criteria andOrderNoLessThanOrEqualTo(String value) {
            addCriterion("ORDER_NO <=", value, "orderNo");
            return this;
        }

        public Criteria andOrderNoLike(String value) {
            addCriterion("ORDER_NO like", value, "orderNo");
            return this;
        }

        public Criteria andOrderNoNotLike(String value) {
            addCriterion("ORDER_NO not like", value, "orderNo");
            return this;
        }

        public Criteria andOrderNoIn(List values) {
            addCriterion("ORDER_NO in", values, "orderNo");
            return this;
        }

        public Criteria andOrderNoNotIn(List values) {
            addCriterion("ORDER_NO not in", values, "orderNo");
            return this;
        }

        public Criteria andOrderNoBetween(String value1, String value2) {
            addCriterion("ORDER_NO between", value1, value2, "orderNo");
            return this;
        }

        public Criteria andOrderNoNotBetween(String value1, String value2) {
            addCriterion("ORDER_NO not between", value1, value2, "orderNo");
            return this;
        }

        public Criteria andPayTimeIsNull() {
            addCriterion("PAY_TIME is null");
            return this;
        }

        public Criteria andPayTimeIsNotNull() {
            addCriterion("PAY_TIME is not null");
            return this;
        }

        public Criteria andPayTimeEqualTo(String value) {
            addCriterion("PAY_TIME =", value, "payTime");
            return this;
        }

        public Criteria andPayTimeNotEqualTo(String value) {
            addCriterion("PAY_TIME <>", value, "payTime");
            return this;
        }

        public Criteria andPayTimeGreaterThan(String value) {
            addCriterion("PAY_TIME >", value, "payTime");
            return this;
        }

        public Criteria andPayTimeGreaterThanOrEqualTo(String value) {
            addCriterion("PAY_TIME >=", value, "payTime");
            return this;
        }

        public Criteria andPayTimeLessThan(String value) {
            addCriterion("PAY_TIME <", value, "payTime");
            return this;
        }

        public Criteria andPayTimeLessThanOrEqualTo(String value) {
            addCriterion("PAY_TIME <=", value, "payTime");
            return this;
        }

        public Criteria andPayTimeLike(String value) {
            addCriterion("PAY_TIME like", value, "payTime");
            return this;
        }

        public Criteria andPayTimeNotLike(String value) {
            addCriterion("PAY_TIME not like", value, "payTime");
            return this;
        }

        public Criteria andPayTimeIn(List values) {
            addCriterion("PAY_TIME in", values, "payTime");
            return this;
        }

        public Criteria andPayTimeNotIn(List values) {
            addCriterion("PAY_TIME not in", values, "payTime");
            return this;
        }

        public Criteria andPayTimeBetween(String value1, String value2) {
            addCriterion("PAY_TIME between", value1, value2, "payTime");
            return this;
        }

        public Criteria andPayTimeNotBetween(String value1, String value2) {
            addCriterion("PAY_TIME not between", value1, value2, "payTime");
            return this;
        }

        public Criteria andPayTypeIsNull() {
            addCriterion("PAY_TYPE is null");
            return this;
        }

        public Criteria andPayTypeIsNotNull() {
            addCriterion("PAY_TYPE is not null");
            return this;
        }

        public Criteria andPayTypeEqualTo(String value) {
            addCriterion("PAY_TYPE =", value, "payType");
            return this;
        }

        public Criteria andPayTypeNotEqualTo(String value) {
            addCriterion("PAY_TYPE <>", value, "payType");
            return this;
        }

        public Criteria andPayTypeGreaterThan(String value) {
            addCriterion("PAY_TYPE >", value, "payType");
            return this;
        }

        public Criteria andPayTypeGreaterThanOrEqualTo(String value) {
            addCriterion("PAY_TYPE >=", value, "payType");
            return this;
        }

        public Criteria andPayTypeLessThan(String value) {
            addCriterion("PAY_TYPE <", value, "payType");
            return this;
        }

        public Criteria andPayTypeLessThanOrEqualTo(String value) {
            addCriterion("PAY_TYPE <=", value, "payType");
            return this;
        }

        public Criteria andPayTypeLike(String value) {
            addCriterion("PAY_TYPE like", value, "payType");
            return this;
        }

        public Criteria andPayTypeNotLike(String value) {
            addCriterion("PAY_TYPE not like", value, "payType");
            return this;
        }

        public Criteria andPayTypeIn(List values) {
            addCriterion("PAY_TYPE in", values, "payType");
            return this;
        }

        public Criteria andPayTypeNotIn(List values) {
            addCriterion("PAY_TYPE not in", values, "payType");
            return this;
        }

        public Criteria andPayTypeBetween(String value1, String value2) {
            addCriterion("PAY_TYPE between", value1, value2, "payType");
            return this;
        }

        public Criteria andPayTypeNotBetween(String value1, String value2) {
            addCriterion("PAY_TYPE not between", value1, value2, "payType");
            return this;
        }

        public Criteria andPayMoneyIsNull() {
            addCriterion("PAY_MONEY is null");
            return this;
        }

        public Criteria andPayMoneyIsNotNull() {
            addCriterion("PAY_MONEY is not null");
            return this;
        }

        public Criteria andPayMoneyEqualTo(String value) {
            addCriterion("PAY_MONEY =", value, "payMoney");
            return this;
        }

        public Criteria andPayMoneyNotEqualTo(String value) {
            addCriterion("PAY_MONEY <>", value, "payMoney");
            return this;
        }

        public Criteria andPayMoneyGreaterThan(String value) {
            addCriterion("PAY_MONEY >", value, "payMoney");
            return this;
        }

        public Criteria andPayMoneyGreaterThanOrEqualTo(String value) {
            addCriterion("PAY_MONEY >=", value, "payMoney");
            return this;
        }

        public Criteria andPayMoneyLessThan(String value) {
            addCriterion("PAY_MONEY <", value, "payMoney");
            return this;
        }

        public Criteria andPayMoneyLessThanOrEqualTo(String value) {
            addCriterion("PAY_MONEY <=", value, "payMoney");
            return this;
        }

        public Criteria andPayMoneyLike(String value) {
            addCriterion("PAY_MONEY like", value, "payMoney");
            return this;
        }

        public Criteria andPayMoneyNotLike(String value) {
            addCriterion("PAY_MONEY not like", value, "payMoney");
            return this;
        }

        public Criteria andPayMoneyIn(List values) {
            addCriterion("PAY_MONEY in", values, "payMoney");
            return this;
        }

        public Criteria andPayMoneyNotIn(List values) {
            addCriterion("PAY_MONEY not in", values, "payMoney");
            return this;
        }

        public Criteria andPayMoneyBetween(String value1, String value2) {
            addCriterion("PAY_MONEY between", value1, value2, "payMoney");
            return this;
        }

        public Criteria andPayMoneyNotBetween(String value1, String value2) {
            addCriterion("PAY_MONEY not between", value1, value2, "payMoney");
            return this;
        }

        public Criteria andInTimeIsNull() {
            addCriterion("IN_TIME is null");
            return this;
        }

        public Criteria andInTimeIsNotNull() {
            addCriterion("IN_TIME is not null");
            return this;
        }

        public Criteria andInTimeEqualTo(String value) {
            addCriterion("IN_TIME =", value, "inTime");
            return this;
        }

        public Criteria andInTimeNotEqualTo(String value) {
            addCriterion("IN_TIME <>", value, "inTime");
            return this;
        }

        public Criteria andInTimeGreaterThan(String value) {
            addCriterion("IN_TIME >", value, "inTime");
            return this;
        }

        public Criteria andInTimeGreaterThanOrEqualTo(String value) {
            addCriterion("IN_TIME >=", value, "inTime");
            return this;
        }

        public Criteria andInTimeLessThan(String value) {
            addCriterion("IN_TIME <", value, "inTime");
            return this;
        }

        public Criteria andInTimeLessThanOrEqualTo(String value) {
            addCriterion("IN_TIME <=", value, "inTime");
            return this;
        }

        public Criteria andInTimeLike(String value) {
            addCriterion("IN_TIME like", value, "inTime");
            return this;
        }

        public Criteria andInTimeNotLike(String value) {
            addCriterion("IN_TIME not like", value, "inTime");
            return this;
        }

        public Criteria andInTimeIn(List values) {
            addCriterion("IN_TIME in", values, "inTime");
            return this;
        }

        public Criteria andInTimeNotIn(List values) {
            addCriterion("IN_TIME not in", values, "inTime");
            return this;
        }

        public Criteria andInTimeBetween(String value1, String value2) {
            addCriterion("IN_TIME between", value1, value2, "inTime");
            return this;
        }

        public Criteria andInTimeNotBetween(String value1, String value2) {
            addCriterion("IN_TIME not between", value1, value2, "inTime");
            return this;
        }

        public Criteria andParkingIdIsNull() {
            addCriterion("PARKING_ID is null");
            return this;
        }

        public Criteria andParkingIdIsNotNull() {
            addCriterion("PARKING_ID is not null");
            return this;
        }

        public Criteria andParkingIdEqualTo(String value) {
            addCriterion("PARKING_ID =", value, "parkingId");
            return this;
        }

        public Criteria andParkingIdNotEqualTo(String value) {
            addCriterion("PARKING_ID <>", value, "parkingId");
            return this;
        }

        public Criteria andParkingIdGreaterThan(String value) {
            addCriterion("PARKING_ID >", value, "parkingId");
            return this;
        }

        public Criteria andParkingIdGreaterThanOrEqualTo(String value) {
            addCriterion("PARKING_ID >=", value, "parkingId");
            return this;
        }

        public Criteria andParkingIdLessThan(String value) {
            addCriterion("PARKING_ID <", value, "parkingId");
            return this;
        }

        public Criteria andParkingIdLessThanOrEqualTo(String value) {
            addCriterion("PARKING_ID <=", value, "parkingId");
            return this;
        }

        public Criteria andParkingIdLike(String value) {
            addCriterion("PARKING_ID like", value, "parkingId");
            return this;
        }

        public Criteria andParkingIdNotLike(String value) {
            addCriterion("PARKING_ID not like", value, "parkingId");
            return this;
        }

        public Criteria andParkingIdIn(List values) {
            addCriterion("PARKING_ID in", values, "parkingId");
            return this;
        }

        public Criteria andParkingIdNotIn(List values) {
            addCriterion("PARKING_ID not in", values, "parkingId");
            return this;
        }

        public Criteria andParkingIdBetween(String value1, String value2) {
            addCriterion("PARKING_ID between", value1, value2, "parkingId");
            return this;
        }

        public Criteria andParkingIdNotBetween(String value1, String value2) {
            addCriterion("PARKING_ID not between", value1, value2, "parkingId");
            return this;
        }

        public Criteria andInDurationIsNull() {
            addCriterion("IN_DURATION is null");
            return this;
        }

        public Criteria andInDurationIsNotNull() {
            addCriterion("IN_DURATION is not null");
            return this;
        }

        public Criteria andInDurationEqualTo(String value) {
            addCriterion("IN_DURATION =", value, "inDuration");
            return this;
        }

        public Criteria andInDurationNotEqualTo(String value) {
            addCriterion("IN_DURATION <>", value, "inDuration");
            return this;
        }

        public Criteria andInDurationGreaterThan(String value) {
            addCriterion("IN_DURATION >", value, "inDuration");
            return this;
        }

        public Criteria andInDurationGreaterThanOrEqualTo(String value) {
            addCriterion("IN_DURATION >=", value, "inDuration");
            return this;
        }

        public Criteria andInDurationLessThan(String value) {
            addCriterion("IN_DURATION <", value, "inDuration");
            return this;
        }

        public Criteria andInDurationLessThanOrEqualTo(String value) {
            addCriterion("IN_DURATION <=", value, "inDuration");
            return this;
        }

        public Criteria andInDurationLike(String value) {
            addCriterion("IN_DURATION like", value, "inDuration");
            return this;
        }

        public Criteria andInDurationNotLike(String value) {
            addCriterion("IN_DURATION not like", value, "inDuration");
            return this;
        }

        public Criteria andInDurationIn(List values) {
            addCriterion("IN_DURATION in", values, "inDuration");
            return this;
        }

        public Criteria andInDurationNotIn(List values) {
            addCriterion("IN_DURATION not in", values, "inDuration");
            return this;
        }

        public Criteria andInDurationBetween(String value1, String value2) {
            addCriterion("IN_DURATION between", value1, value2, "inDuration");
            return this;
        }

        public Criteria andInDurationNotBetween(String value1, String value2) {
            addCriterion("IN_DURATION not between", value1, value2, "inDuration");
            return this;
        }

        public Criteria andCardNumberIsNull() {
            addCriterion("CARD_NUMBER is null");
            return this;
        }

        public Criteria andCardNumberIsNotNull() {
            addCriterion("CARD_NUMBER is not null");
            return this;
        }

        public Criteria andCardNumberEqualTo(String value) {
            addCriterion("CARD_NUMBER =", value, "cardNumber");
            return this;
        }

        public Criteria andCardNumberNotEqualTo(String value) {
            addCriterion("CARD_NUMBER <>", value, "cardNumber");
            return this;
        }

        public Criteria andCardNumberGreaterThan(String value) {
            addCriterion("CARD_NUMBER >", value, "cardNumber");
            return this;
        }

        public Criteria andCardNumberGreaterThanOrEqualTo(String value) {
            addCriterion("CARD_NUMBER >=", value, "cardNumber");
            return this;
        }

        public Criteria andCardNumberLessThan(String value) {
            addCriterion("CARD_NUMBER <", value, "cardNumber");
            return this;
        }

        public Criteria andCardNumberLessThanOrEqualTo(String value) {
            addCriterion("CARD_NUMBER <=", value, "cardNumber");
            return this;
        }

        public Criteria andCardNumberLike(String value) {
            addCriterion("CARD_NUMBER like", value, "cardNumber");
            return this;
        }

        public Criteria andCardNumberNotLike(String value) {
            addCriterion("CARD_NUMBER not like", value, "cardNumber");
            return this;
        }

        public Criteria andCardNumberIn(List values) {
            addCriterion("CARD_NUMBER in", values, "cardNumber");
            return this;
        }

        public Criteria andCardNumberNotIn(List values) {
            addCriterion("CARD_NUMBER not in", values, "cardNumber");
            return this;
        }

        public Criteria andCardNumberBetween(String value1, String value2) {
            addCriterion("CARD_NUMBER between", value1, value2, "cardNumber");
            return this;
        }

        public Criteria andCardNumberNotBetween(String value1, String value2) {
            addCriterion("CARD_NUMBER not between", value1, value2, "cardNumber");
            return this;
        }

        public Criteria andDiscountMoneyIsNull() {
            addCriterion("DISCOUNT_MONEY is null");
            return this;
        }

        public Criteria andDiscountMoneyIsNotNull() {
            addCriterion("DISCOUNT_MONEY is not null");
            return this;
        }

        public Criteria andDiscountMoneyEqualTo(BigDecimal value) {
            addCriterion("DISCOUNT_MONEY =", value, "discountMoney");
            return this;
        }

        public Criteria andDiscountMoneyNotEqualTo(BigDecimal value) {
            addCriterion("DISCOUNT_MONEY <>", value, "discountMoney");
            return this;
        }

        public Criteria andDiscountMoneyGreaterThan(BigDecimal value) {
            addCriterion("DISCOUNT_MONEY >", value, "discountMoney");
            return this;
        }

        public Criteria andDiscountMoneyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("DISCOUNT_MONEY >=", value, "discountMoney");
            return this;
        }

        public Criteria andDiscountMoneyLessThan(BigDecimal value) {
            addCriterion("DISCOUNT_MONEY <", value, "discountMoney");
            return this;
        }

        public Criteria andDiscountMoneyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("DISCOUNT_MONEY <=", value, "discountMoney");
            return this;
        }

        public Criteria andDiscountMoneyIn(List values) {
            addCriterion("DISCOUNT_MONEY in", values, "discountMoney");
            return this;
        }

        public Criteria andDiscountMoneyNotIn(List values) {
            addCriterion("DISCOUNT_MONEY not in", values, "discountMoney");
            return this;
        }

        public Criteria andDiscountMoneyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("DISCOUNT_MONEY between", value1, value2, "discountMoney");
            return this;
        }

        public Criteria andDiscountMoneyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("DISCOUNT_MONEY not between", value1, value2, "discountMoney");
            return this;
        }

        public Criteria andPaidMoneyIsNull() {
            addCriterion("PAID_MONEY is null");
            return this;
        }

        public Criteria andPaidMoneyIsNotNull() {
            addCriterion("PAID_MONEY is not null");
            return this;
        }

        public Criteria andPaidMoneyEqualTo(BigDecimal value) {
            addCriterion("PAID_MONEY =", value, "paidMoney");
            return this;
        }

        public Criteria andPaidMoneyNotEqualTo(BigDecimal value) {
            addCriterion("PAID_MONEY <>", value, "paidMoney");
            return this;
        }

        public Criteria andPaidMoneyGreaterThan(BigDecimal value) {
            addCriterion("PAID_MONEY >", value, "paidMoney");
            return this;
        }

        public Criteria andPaidMoneyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("PAID_MONEY >=", value, "paidMoney");
            return this;
        }

        public Criteria andPaidMoneyLessThan(BigDecimal value) {
            addCriterion("PAID_MONEY <", value, "paidMoney");
            return this;
        }

        public Criteria andPaidMoneyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("PAID_MONEY <=", value, "paidMoney");
            return this;
        }

        public Criteria andPaidMoneyIn(List values) {
            addCriterion("PAID_MONEY in", values, "paidMoney");
            return this;
        }

        public Criteria andPaidMoneyNotIn(List values) {
            addCriterion("PAID_MONEY not in", values, "paidMoney");
            return this;
        }

        public Criteria andPaidMoneyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PAID_MONEY between", value1, value2, "paidMoney");
            return this;
        }

        public Criteria andPaidMoneyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PAID_MONEY not between", value1, value2, "paidMoney");
            return this;
        }

        public Criteria andSellerIdIsNull() {
            addCriterion("SELLER_ID is null");
            return this;
        }

        public Criteria andSellerIdIsNotNull() {
            addCriterion("SELLER_ID is not null");
            return this;
        }

        public Criteria andSellerIdEqualTo(String value) {
            addCriterion("SELLER_ID =", value, "sellerId");
            return this;
        }

        public Criteria andSellerIdNotEqualTo(String value) {
            addCriterion("SELLER_ID <>", value, "sellerId");
            return this;
        }

        public Criteria andSellerIdGreaterThan(String value) {
            addCriterion("SELLER_ID >", value, "sellerId");
            return this;
        }

        public Criteria andSellerIdGreaterThanOrEqualTo(String value) {
            addCriterion("SELLER_ID >=", value, "sellerId");
            return this;
        }

        public Criteria andSellerIdLessThan(String value) {
            addCriterion("SELLER_ID <", value, "sellerId");
            return this;
        }

        public Criteria andSellerIdLessThanOrEqualTo(String value) {
            addCriterion("SELLER_ID <=", value, "sellerId");
            return this;
        }

        public Criteria andSellerIdLike(String value) {
            addCriterion("SELLER_ID like", value, "sellerId");
            return this;
        }

        public Criteria andSellerIdNotLike(String value) {
            addCriterion("SELLER_ID not like", value, "sellerId");
            return this;
        }

        public Criteria andSellerIdIn(List values) {
            addCriterion("SELLER_ID in", values, "sellerId");
            return this;
        }

        public Criteria andSellerIdNotIn(List values) {
            addCriterion("SELLER_ID not in", values, "sellerId");
            return this;
        }

        public Criteria andSellerIdBetween(String value1, String value2) {
            addCriterion("SELLER_ID between", value1, value2, "sellerId");
            return this;
        }

        public Criteria andSellerIdNotBetween(String value1, String value2) {
            addCriterion("SELLER_ID not between", value1, value2, "sellerId");
            return this;
        }

        public Criteria andOutTimeIsNull() {
            addCriterion("OUT_TIME is null");
            return this;
        }

        public Criteria andOutTimeIsNotNull() {
            addCriterion("OUT_TIME is not null");
            return this;
        }

        public Criteria andOutTimeEqualTo(String value) {
            addCriterion("OUT_TIME =", value, "outTime");
            return this;
        }

        public Criteria andOutTimeNotEqualTo(String value) {
            addCriterion("OUT_TIME <>", value, "outTime");
            return this;
        }

        public Criteria andOutTimeGreaterThan(String value) {
            addCriterion("OUT_TIME >", value, "outTime");
            return this;
        }

        public Criteria andOutTimeGreaterThanOrEqualTo(String value) {
            addCriterion("OUT_TIME >=", value, "outTime");
            return this;
        }

        public Criteria andOutTimeLessThan(String value) {
            addCriterion("OUT_TIME <", value, "outTime");
            return this;
        }

        public Criteria andOutTimeLessThanOrEqualTo(String value) {
            addCriterion("OUT_TIME <=", value, "outTime");
            return this;
        }

        public Criteria andOutTimeLike(String value) {
            addCriterion("OUT_TIME like", value, "outTime");
            return this;
        }

        public Criteria andOutTimeNotLike(String value) {
            addCriterion("OUT_TIME not like", value, "outTime");
            return this;
        }

        public Criteria andOutTimeIn(List values) {
            addCriterion("OUT_TIME in", values, "outTime");
            return this;
        }

        public Criteria andOutTimeNotIn(List values) {
            addCriterion("OUT_TIME not in", values, "outTime");
            return this;
        }

        public Criteria andOutTimeBetween(String value1, String value2) {
            addCriterion("OUT_TIME between", value1, value2, "outTime");
            return this;
        }

        public Criteria andOutTimeNotBetween(String value1, String value2) {
            addCriterion("OUT_TIME not between", value1, value2, "outTime");
            return this;
        }

        public Criteria andOrderSynStatusIsNull() {
            addCriterion("ORDER_SYN_STATUS is null");
            return this;
        }

        public Criteria andOrderSynStatusIsNotNull() {
            addCriterion("ORDER_SYN_STATUS is not null");
            return this;
        }

        public Criteria andOrderSynStatusEqualTo(String value) {
            addCriterion("ORDER_SYN_STATUS =", value, "orderSynStatus");
            return this;
        }

        public Criteria andOrderSynStatusNotEqualTo(String value) {
            addCriterion("ORDER_SYN_STATUS <>", value, "orderSynStatus");
            return this;
        }

        public Criteria andOrderSynStatusGreaterThan(String value) {
            addCriterion("ORDER_SYN_STATUS >", value, "orderSynStatus");
            return this;
        }

        public Criteria andOrderSynStatusGreaterThanOrEqualTo(String value) {
            addCriterion("ORDER_SYN_STATUS >=", value, "orderSynStatus");
            return this;
        }

        public Criteria andOrderSynStatusLessThan(String value) {
            addCriterion("ORDER_SYN_STATUS <", value, "orderSynStatus");
            return this;
        }

        public Criteria andOrderSynStatusLessThanOrEqualTo(String value) {
            addCriterion("ORDER_SYN_STATUS <=", value, "orderSynStatus");
            return this;
        }

        public Criteria andOrderSynStatusLike(String value) {
            addCriterion("ORDER_SYN_STATUS like", value, "orderSynStatus");
            return this;
        }

        public Criteria andOrderSynStatusNotLike(String value) {
            addCriterion("ORDER_SYN_STATUS not like", value, "orderSynStatus");
            return this;
        }

        public Criteria andOrderSynStatusIn(List values) {
            addCriterion("ORDER_SYN_STATUS in", values, "orderSynStatus");
            return this;
        }

        public Criteria andOrderSynStatusNotIn(List values) {
            addCriterion("ORDER_SYN_STATUS not in", values, "orderSynStatus");
            return this;
        }

        public Criteria andOrderSynStatusBetween(String value1, String value2) {
            addCriterion("ORDER_SYN_STATUS between", value1, value2, "orderSynStatus");
            return this;
        }

        public Criteria andOrderSynStatusNotBetween(String value1, String value2) {
            addCriterion("ORDER_SYN_STATUS not between", value1, value2, "orderSynStatus");
            return this;
        }

        public Criteria andOrderPayStatusIsNull() {
            addCriterion("ORDER_PAY_STATUS is null");
            return this;
        }

        public Criteria andOrderPayStatusIsNotNull() {
            addCriterion("ORDER_PAY_STATUS is not null");
            return this;
        }

        public Criteria andOrderPayStatusEqualTo(String value) {
            addCriterion("ORDER_PAY_STATUS =", value, "orderPayStatus");
            return this;
        }

        public Criteria andOrderPayStatusNotEqualTo(String value) {
            addCriterion("ORDER_PAY_STATUS <>", value, "orderPayStatus");
            return this;
        }

        public Criteria andOrderPayStatusGreaterThan(String value) {
            addCriterion("ORDER_PAY_STATUS >", value, "orderPayStatus");
            return this;
        }

        public Criteria andOrderPayStatusGreaterThanOrEqualTo(String value) {
            addCriterion("ORDER_PAY_STATUS >=", value, "orderPayStatus");
            return this;
        }

        public Criteria andOrderPayStatusLessThan(String value) {
            addCriterion("ORDER_PAY_STATUS <", value, "orderPayStatus");
            return this;
        }

        public Criteria andOrderPayStatusLessThanOrEqualTo(String value) {
            addCriterion("ORDER_PAY_STATUS <=", value, "orderPayStatus");
            return this;
        }

        public Criteria andOrderPayStatusLike(String value) {
            addCriterion("ORDER_PAY_STATUS like", value, "orderPayStatus");
            return this;
        }

        public Criteria andOrderPayStatusNotLike(String value) {
            addCriterion("ORDER_PAY_STATUS not like", value, "orderPayStatus");
            return this;
        }

        public Criteria andOrderPayStatusIn(List values) {
            addCriterion("ORDER_PAY_STATUS in", values, "orderPayStatus");
            return this;
        }

        public Criteria andOrderPayStatusNotIn(List values) {
            addCriterion("ORDER_PAY_STATUS not in", values, "orderPayStatus");
            return this;
        }

        public Criteria andOrderPayStatusBetween(String value1, String value2) {
            addCriterion("ORDER_PAY_STATUS between", value1, value2, "orderPayStatus");
            return this;
        }

        public Criteria andOrderPayStatusNotBetween(String value1, String value2) {
            addCriterion("ORDER_PAY_STATUS not between", value1, value2, "orderPayStatus");
            return this;
        }

        public Criteria andCarIdIsNull() {
            addCriterion("CAR_ID is null");
            return this;
        }

        public Criteria andCarIdIsNotNull() {
            addCriterion("CAR_ID is not null");
            return this;
        }

        public Criteria andCarIdEqualTo(String value) {
            addCriterion("CAR_ID =", value, "carId");
            return this;
        }

        public Criteria andCarIdNotEqualTo(String value) {
            addCriterion("CAR_ID <>", value, "carId");
            return this;
        }

        public Criteria andCarIdGreaterThan(String value) {
            addCriterion("CAR_ID >", value, "carId");
            return this;
        }

        public Criteria andCarIdGreaterThanOrEqualTo(String value) {
            addCriterion("CAR_ID >=", value, "carId");
            return this;
        }

        public Criteria andCarIdLessThan(String value) {
            addCriterion("CAR_ID <", value, "carId");
            return this;
        }

        public Criteria andCarIdLessThanOrEqualTo(String value) {
            addCriterion("CAR_ID <=", value, "carId");
            return this;
        }

        public Criteria andCarIdLike(String value) {
            addCriterion("CAR_ID like", value, "carId");
            return this;
        }

        public Criteria andCarIdNotLike(String value) {
            addCriterion("CAR_ID not like", value, "carId");
            return this;
        }

        public Criteria andCarIdIn(List values) {
            addCriterion("CAR_ID in", values, "carId");
            return this;
        }

        public Criteria andCarIdNotIn(List values) {
            addCriterion("CAR_ID not in", values, "carId");
            return this;
        }

        public Criteria andCarIdBetween(String value1, String value2) {
            addCriterion("CAR_ID between", value1, value2, "carId");
            return this;
        }

        public Criteria andCarIdNotBetween(String value1, String value2) {
            addCriterion("CAR_ID not between", value1, value2, "carId");
            return this;
        }

        public Criteria andCarColorIsNull() {
            addCriterion("CAR_COLOR is null");
            return this;
        }

        public Criteria andCarColorIsNotNull() {
            addCriterion("CAR_COLOR is not null");
            return this;
        }

        public Criteria andCarColorEqualTo(String value) {
            addCriterion("CAR_COLOR =", value, "carColor");
            return this;
        }

        public Criteria andCarColorNotEqualTo(String value) {
            addCriterion("CAR_COLOR <>", value, "carColor");
            return this;
        }

        public Criteria andCarColorGreaterThan(String value) {
            addCriterion("CAR_COLOR >", value, "carColor");
            return this;
        }

        public Criteria andCarColorGreaterThanOrEqualTo(String value) {
            addCriterion("CAR_COLOR >=", value, "carColor");
            return this;
        }

        public Criteria andCarColorLessThan(String value) {
            addCriterion("CAR_COLOR <", value, "carColor");
            return this;
        }

        public Criteria andCarColorLessThanOrEqualTo(String value) {
            addCriterion("CAR_COLOR <=", value, "carColor");
            return this;
        }

        public Criteria andCarColorLike(String value) {
            addCriterion("CAR_COLOR like", value, "carColor");
            return this;
        }

        public Criteria andCarColorNotLike(String value) {
            addCriterion("CAR_COLOR not like", value, "carColor");
            return this;
        }

        public Criteria andCarColorIn(List values) {
            addCriterion("CAR_COLOR in", values, "carColor");
            return this;
        }

        public Criteria andCarColorNotIn(List values) {
            addCriterion("CAR_COLOR not in", values, "carColor");
            return this;
        }

        public Criteria andCarColorBetween(String value1, String value2) {
            addCriterion("CAR_COLOR between", value1, value2, "carColor");
            return this;
        }

        public Criteria andCarColorNotBetween(String value1, String value2) {
            addCriterion("CAR_COLOR not between", value1, value2, "carColor");
            return this;
        }

        public Criteria andCarTypeIsNull() {
            addCriterion("CAR_TYPE is null");
            return this;
        }

        public Criteria andCarTypeIsNotNull() {
            addCriterion("CAR_TYPE is not null");
            return this;
        }

        public Criteria andCarTypeEqualTo(String value) {
            addCriterion("CAR_TYPE =", value, "carType");
            return this;
        }

        public Criteria andCarTypeNotEqualTo(String value) {
            addCriterion("CAR_TYPE <>", value, "carType");
            return this;
        }

        public Criteria andCarTypeGreaterThan(String value) {
            addCriterion("CAR_TYPE >", value, "carType");
            return this;
        }

        public Criteria andCarTypeGreaterThanOrEqualTo(String value) {
            addCriterion("CAR_TYPE >=", value, "carType");
            return this;
        }

        public Criteria andCarTypeLessThan(String value) {
            addCriterion("CAR_TYPE <", value, "carType");
            return this;
        }

        public Criteria andCarTypeLessThanOrEqualTo(String value) {
            addCriterion("CAR_TYPE <=", value, "carType");
            return this;
        }

        public Criteria andCarTypeLike(String value) {
            addCriterion("CAR_TYPE like", value, "carType");
            return this;
        }

        public Criteria andCarTypeNotLike(String value) {
            addCriterion("CAR_TYPE not like", value, "carType");
            return this;
        }

        public Criteria andCarTypeIn(List values) {
            addCriterion("CAR_TYPE in", values, "carType");
            return this;
        }

        public Criteria andCarTypeNotIn(List values) {
            addCriterion("CAR_TYPE not in", values, "carType");
            return this;
        }

        public Criteria andCarTypeBetween(String value1, String value2) {
            addCriterion("CAR_TYPE between", value1, value2, "carType");
            return this;
        }

        public Criteria andCarTypeNotBetween(String value1, String value2) {
            addCriterion("CAR_TYPE not between", value1, value2, "carType");
            return this;
        }

        public Criteria andOrderTradeIsNull() {
            addCriterion("ORDER_TRADE is null");
            return this;
        }

        public Criteria andOrderTradeIsNotNull() {
            addCriterion("ORDER_TRADE is not null");
            return this;
        }

        public Criteria andOrderTradeEqualTo(String value) {
            addCriterion("ORDER_TRADE =", value, "orderTrade");
            return this;
        }

        public Criteria andOrderTradeNotEqualTo(String value) {
            addCriterion("ORDER_TRADE <>", value, "orderTrade");
            return this;
        }

        public Criteria andOrderTradeGreaterThan(String value) {
            addCriterion("ORDER_TRADE >", value, "orderTrade");
            return this;
        }

        public Criteria andOrderTradeGreaterThanOrEqualTo(String value) {
            addCriterion("ORDER_TRADE >=", value, "orderTrade");
            return this;
        }

        public Criteria andOrderTradeLessThan(String value) {
            addCriterion("ORDER_TRADE <", value, "orderTrade");
            return this;
        }

        public Criteria andOrderTradeLessThanOrEqualTo(String value) {
            addCriterion("ORDER_TRADE <=", value, "orderTrade");
            return this;
        }

        public Criteria andOrderTradeLike(String value) {
            addCriterion("ORDER_TRADE like", value, "orderTrade");
            return this;
        }

        public Criteria andOrderTradeNotLike(String value) {
            addCriterion("ORDER_TRADE not like", value, "orderTrade");
            return this;
        }

        public Criteria andOrderTradeIn(List values) {
            addCriterion("ORDER_TRADE in", values, "orderTrade");
            return this;
        }

        public Criteria andOrderTradeNotIn(List values) {
            addCriterion("ORDER_TRADE not in", values, "orderTrade");
            return this;
        }

        public Criteria andOrderTradeBetween(String value1, String value2) {
            addCriterion("ORDER_TRADE between", value1, value2, "orderTrade");
            return this;
        }

        public Criteria andOrderTradeNotBetween(String value1, String value2) {
            addCriterion("ORDER_TRADE not between", value1, value2, "orderTrade");
            return this;
        }
    }
}