package com.compass.order.model;

import java.math.BigDecimal;
import java.util.Date;

public class OrderPayBean {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TB_ORDER_PAY.ORDER_ID
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    private String orderId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TB_ORDER_PAY.USER_ID
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    private String userId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TB_ORDER_PAY.OUT_PARKING_ID
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    private String outParkingId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TB_ORDER_PAY.PARKING_NAME
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    private String parkingName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TB_ORDER_PAY.CAR_NUMBER
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    private String carNumber;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TB_ORDER_PAY.OUT_ORDER_NO
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    private String outOrderNo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TB_ORDER_PAY.ORDER_STATUS
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    private String orderStatus;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TB_ORDER_PAY.ORDER_TIME
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    private String orderTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TB_ORDER_PAY.ORDER_NO
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    private String orderNo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TB_ORDER_PAY.PAY_TIME
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    private String payTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TB_ORDER_PAY.PAY_TYPE
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    private String payType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TB_ORDER_PAY.PAY_MONEY
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    private String payMoney;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TB_ORDER_PAY.IN_TIME
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    private String inTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TB_ORDER_PAY.PARKING_ID
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    private String parkingId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TB_ORDER_PAY.IN_DURATION
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    private String inDuration;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TB_ORDER_PAY.CARD_NUMBER
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    private String cardNumber;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TB_ORDER_PAY.DISCOUNT_MONEY
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    private BigDecimal discountMoney;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TB_ORDER_PAY.PAID_MONEY
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    private BigDecimal paidMoney;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TB_ORDER_PAY.SELLER_ID
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    private String sellerId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TB_ORDER_PAY.OUT_TIME
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    private String outTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TB_ORDER_PAY.ORDER_SYN_STATUS
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    private String orderSynStatus;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TB_ORDER_PAY.ORDER_PAY_STATUS
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    private String orderPayStatus;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TB_ORDER_PAY.CAR_ID
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    private String carId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TB_ORDER_PAY.CAR_COLOR
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    private String carColor;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TB_ORDER_PAY.CAR_TYPE
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    private String carType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TB_ORDER_PAY.ORDER_TRADE
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    private String orderTrade;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TB_ORDER_PAY.ORDER_ID
     *
     * @return the value of TB_ORDER_PAY.ORDER_ID
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TB_ORDER_PAY.ORDER_ID
     *
     * @param orderId the value for TB_ORDER_PAY.ORDER_ID
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TB_ORDER_PAY.USER_ID
     *
     * @return the value of TB_ORDER_PAY.USER_ID
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TB_ORDER_PAY.USER_ID
     *
     * @param userId the value for TB_ORDER_PAY.USER_ID
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TB_ORDER_PAY.OUT_PARKING_ID
     *
     * @return the value of TB_ORDER_PAY.OUT_PARKING_ID
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    public String getOutParkingId() {
        return outParkingId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TB_ORDER_PAY.OUT_PARKING_ID
     *
     * @param outParkingId the value for TB_ORDER_PAY.OUT_PARKING_ID
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    public void setOutParkingId(String outParkingId) {
        this.outParkingId = outParkingId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TB_ORDER_PAY.PARKING_NAME
     *
     * @return the value of TB_ORDER_PAY.PARKING_NAME
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    public String getParkingName() {
        return parkingName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TB_ORDER_PAY.PARKING_NAME
     *
     * @param parkingName the value for TB_ORDER_PAY.PARKING_NAME
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    public void setParkingName(String parkingName) {
        this.parkingName = parkingName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TB_ORDER_PAY.CAR_NUMBER
     *
     * @return the value of TB_ORDER_PAY.CAR_NUMBER
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    public String getCarNumber() {
        return carNumber;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TB_ORDER_PAY.CAR_NUMBER
     *
     * @param carNumber the value for TB_ORDER_PAY.CAR_NUMBER
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    public void setCarNumber(String carNumber) {
        this.carNumber = carNumber;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TB_ORDER_PAY.OUT_ORDER_NO
     *
     * @return the value of TB_ORDER_PAY.OUT_ORDER_NO
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    public String getOutOrderNo() {
        return outOrderNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TB_ORDER_PAY.OUT_ORDER_NO
     *
     * @param outOrderNo the value for TB_ORDER_PAY.OUT_ORDER_NO
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    public void setOutOrderNo(String outOrderNo) {
        this.outOrderNo = outOrderNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TB_ORDER_PAY.ORDER_STATUS
     *
     * @return the value of TB_ORDER_PAY.ORDER_STATUS
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TB_ORDER_PAY.ORDER_STATUS
     *
     * @param orderStatus the value for TB_ORDER_PAY.ORDER_STATUS
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TB_ORDER_PAY.ORDER_TIME
     *
     * @return the value of TB_ORDER_PAY.ORDER_TIME
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    public String getOrderTime() {
        return orderTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TB_ORDER_PAY.ORDER_TIME
     *
     * @param orderTime the value for TB_ORDER_PAY.ORDER_TIME
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    public void setOrderTime(String orderTime) {
        this.orderTime = orderTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TB_ORDER_PAY.ORDER_NO
     *
     * @return the value of TB_ORDER_PAY.ORDER_NO
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TB_ORDER_PAY.ORDER_NO
     *
     * @param orderNo the value for TB_ORDER_PAY.ORDER_NO
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TB_ORDER_PAY.PAY_TIME
     *
     * @return the value of TB_ORDER_PAY.PAY_TIME
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    public String getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TB_ORDER_PAY.PAY_TIME
     *
     * @param payTime the value for TB_ORDER_PAY.PAY_TIME
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    public void setPayTime(String payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TB_ORDER_PAY.PAY_TYPE
     *
     * @return the value of TB_ORDER_PAY.PAY_TYPE
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    public String getPayType() {
        return payType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TB_ORDER_PAY.PAY_TYPE
     *
     * @param payType the value for TB_ORDER_PAY.PAY_TYPE
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    public void setPayType(String payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TB_ORDER_PAY.PAY_MONEY
     *
     * @return the value of TB_ORDER_PAY.PAY_MONEY
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    public String getPayMoney() {
        return payMoney;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TB_ORDER_PAY.PAY_MONEY
     *
     * @param payMoney the value for TB_ORDER_PAY.PAY_MONEY
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    public void setPayMoney(String payMoney) {
        this.payMoney = payMoney;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TB_ORDER_PAY.IN_TIME
     *
     * @return the value of TB_ORDER_PAY.IN_TIME
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    public String getInTime() {
        return inTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TB_ORDER_PAY.IN_TIME
     *
     * @param inTime the value for TB_ORDER_PAY.IN_TIME
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    public void setInTime(String inTime) {
        this.inTime = inTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TB_ORDER_PAY.PARKING_ID
     *
     * @return the value of TB_ORDER_PAY.PARKING_ID
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    public String getParkingId() {
        return parkingId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TB_ORDER_PAY.PARKING_ID
     *
     * @param parkingId the value for TB_ORDER_PAY.PARKING_ID
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    public void setParkingId(String parkingId) {
        this.parkingId = parkingId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TB_ORDER_PAY.IN_DURATION
     *
     * @return the value of TB_ORDER_PAY.IN_DURATION
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    public String getInDuration() {
        return inDuration;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TB_ORDER_PAY.IN_DURATION
     *
     * @param inDuration the value for TB_ORDER_PAY.IN_DURATION
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    public void setInDuration(String inDuration) {
        this.inDuration = inDuration;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TB_ORDER_PAY.CARD_NUMBER
     *
     * @return the value of TB_ORDER_PAY.CARD_NUMBER
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    public String getCardNumber() {
        return cardNumber;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TB_ORDER_PAY.CARD_NUMBER
     *
     * @param cardNumber the value for TB_ORDER_PAY.CARD_NUMBER
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    public void setCardNumber(String cardNumber) {
        this.cardNumber = cardNumber;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TB_ORDER_PAY.DISCOUNT_MONEY
     *
     * @return the value of TB_ORDER_PAY.DISCOUNT_MONEY
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    public BigDecimal getDiscountMoney() {
        return discountMoney;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TB_ORDER_PAY.DISCOUNT_MONEY
     *
     * @param discountMoney the value for TB_ORDER_PAY.DISCOUNT_MONEY
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    public void setDiscountMoney(BigDecimal discountMoney) {
        this.discountMoney = discountMoney;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TB_ORDER_PAY.PAID_MONEY
     *
     * @return the value of TB_ORDER_PAY.PAID_MONEY
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    public BigDecimal getPaidMoney() {
        return paidMoney;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TB_ORDER_PAY.PAID_MONEY
     *
     * @param paidMoney the value for TB_ORDER_PAY.PAID_MONEY
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    public void setPaidMoney(BigDecimal paidMoney) {
        this.paidMoney = paidMoney;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TB_ORDER_PAY.SELLER_ID
     *
     * @return the value of TB_ORDER_PAY.SELLER_ID
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    public String getSellerId() {
        return sellerId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TB_ORDER_PAY.SELLER_ID
     *
     * @param sellerId the value for TB_ORDER_PAY.SELLER_ID
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    public void setSellerId(String sellerId) {
        this.sellerId = sellerId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TB_ORDER_PAY.OUT_TIME
     *
     * @return the value of TB_ORDER_PAY.OUT_TIME
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    public String getOutTime() {
        return outTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TB_ORDER_PAY.OUT_TIME
     *
     * @param outTime the value for TB_ORDER_PAY.OUT_TIME
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    public void setOutTime(String outTime) {
        this.outTime = outTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TB_ORDER_PAY.ORDER_SYN_STATUS
     *
     * @return the value of TB_ORDER_PAY.ORDER_SYN_STATUS
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    public String getOrderSynStatus() {
        return orderSynStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TB_ORDER_PAY.ORDER_SYN_STATUS
     *
     * @param orderSynStatus the value for TB_ORDER_PAY.ORDER_SYN_STATUS
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    public void setOrderSynStatus(String orderSynStatus) {
        this.orderSynStatus = orderSynStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TB_ORDER_PAY.ORDER_PAY_STATUS
     *
     * @return the value of TB_ORDER_PAY.ORDER_PAY_STATUS
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    public String getOrderPayStatus() {
        return orderPayStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TB_ORDER_PAY.ORDER_PAY_STATUS
     *
     * @param orderPayStatus the value for TB_ORDER_PAY.ORDER_PAY_STATUS
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    public void setOrderPayStatus(String orderPayStatus) {
        this.orderPayStatus = orderPayStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TB_ORDER_PAY.CAR_ID
     *
     * @return the value of TB_ORDER_PAY.CAR_ID
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    public String getCarId() {
        return carId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TB_ORDER_PAY.CAR_ID
     *
     * @param carId the value for TB_ORDER_PAY.CAR_ID
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    public void setCarId(String carId) {
        this.carId = carId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TB_ORDER_PAY.CAR_COLOR
     *
     * @return the value of TB_ORDER_PAY.CAR_COLOR
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    public String getCarColor() {
        return carColor;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TB_ORDER_PAY.CAR_COLOR
     *
     * @param carColor the value for TB_ORDER_PAY.CAR_COLOR
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    public void setCarColor(String carColor) {
        this.carColor = carColor;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TB_ORDER_PAY.CAR_TYPE
     *
     * @return the value of TB_ORDER_PAY.CAR_TYPE
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    public String getCarType() {
        return carType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TB_ORDER_PAY.CAR_TYPE
     *
     * @param carType the value for TB_ORDER_PAY.CAR_TYPE
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    public void setCarType(String carType) {
        this.carType = carType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TB_ORDER_PAY.ORDER_TRADE
     *
     * @return the value of TB_ORDER_PAY.ORDER_TRADE
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    public String getOrderTrade() {
        return orderTrade;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TB_ORDER_PAY.ORDER_TRADE
     *
     * @param orderTrade the value for TB_ORDER_PAY.ORDER_TRADE
     *
     * @ibatorgenerated Fri Nov 24 20:37:33 CST 2017
     */
    public void setOrderTrade(String orderTrade) {
        this.orderTrade = orderTrade;
    }
    private Integer start;
	private Integer end;
	private Date startDate;
	private Date endDate;

	public Integer getStart() {
		return start;
	}

	public void setStart(Integer start) {
		this.start = start;
	}

	public Integer getEnd() {
		return end;
	}

	public void setEnd(Integer end) {
		this.end = end;
	}

	public Date getStartDate() {
		return startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}
}