package com.compass.order.model;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class OrderBeanExample {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table PARK.TB_ORDER
     *
     * @ibatorgenerated Thu Nov 02 21:11:57 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table PARK.TB_ORDER
     *
     * @ibatorgenerated Thu Nov 02 21:11:57 CST 2017
     */
    protected List oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PARK.TB_ORDER
     *
     * @ibatorgenerated Thu Nov 02 21:11:57 CST 2017
     */
    public OrderBeanExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PARK.TB_ORDER
     *
     * @ibatorgenerated Thu Nov 02 21:11:57 CST 2017
     */
    protected OrderBeanExample(OrderBeanExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PARK.TB_ORDER
     *
     * @ibatorgenerated Thu Nov 02 21:11:57 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PARK.TB_ORDER
     *
     * @ibatorgenerated Thu Nov 02 21:11:57 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PARK.TB_ORDER
     *
     * @ibatorgenerated Thu Nov 02 21:11:57 CST 2017
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PARK.TB_ORDER
     *
     * @ibatorgenerated Thu Nov 02 21:11:57 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PARK.TB_ORDER
     *
     * @ibatorgenerated Thu Nov 02 21:11:57 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PARK.TB_ORDER
     *
     * @ibatorgenerated Thu Nov 02 21:11:57 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table PARK.TB_ORDER
     *
     * @ibatorgenerated Thu Nov 02 21:11:57 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table PARK.TB_ORDER
     *
     * @ibatorgenerated Thu Nov 02 21:11:57 CST 2017
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andOrderNoIsNull() {
            addCriterion("ORDER_NO is null");
            return this;
        }

        public Criteria andOrderNoIsNotNull() {
            addCriterion("ORDER_NO is not null");
            return this;
        }

        public Criteria andOrderNoEqualTo(String value) {
            addCriterion("ORDER_NO =", value, "orderNo");
            return this;
        }

        public Criteria andOrderNoNotEqualTo(String value) {
            addCriterion("ORDER_NO <>", value, "orderNo");
            return this;
        }

        public Criteria andOrderNoGreaterThan(String value) {
            addCriterion("ORDER_NO >", value, "orderNo");
            return this;
        }

        public Criteria andOrderNoGreaterThanOrEqualTo(String value) {
            addCriterion("ORDER_NO >=", value, "orderNo");
            return this;
        }

        public Criteria andOrderNoLessThan(String value) {
            addCriterion("ORDER_NO <", value, "orderNo");
            return this;
        }

        public Criteria andOrderNoLessThanOrEqualTo(String value) {
            addCriterion("ORDER_NO <=", value, "orderNo");
            return this;
        }

        public Criteria andOrderNoLike(String value) {
            addCriterion("ORDER_NO like", value, "orderNo");
            return this;
        }

        public Criteria andOrderNoNotLike(String value) {
            addCriterion("ORDER_NO not like", value, "orderNo");
            return this;
        }

        public Criteria andOrderNoIn(List values) {
            addCriterion("ORDER_NO in", values, "orderNo");
            return this;
        }

        public Criteria andOrderNoNotIn(List values) {
            addCriterion("ORDER_NO not in", values, "orderNo");
            return this;
        }

        public Criteria andOrderNoBetween(String value1, String value2) {
            addCriterion("ORDER_NO between", value1, value2, "orderNo");
            return this;
        }

        public Criteria andOrderNoNotBetween(String value1, String value2) {
            addCriterion("ORDER_NO not between", value1, value2, "orderNo");
            return this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("USER_ID is null");
            return this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("USER_ID is not null");
            return this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("USER_ID =", value, "userId");
            return this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("USER_ID <>", value, "userId");
            return this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("USER_ID >", value, "userId");
            return this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("USER_ID >=", value, "userId");
            return this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("USER_ID <", value, "userId");
            return this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("USER_ID <=", value, "userId");
            return this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("USER_ID like", value, "userId");
            return this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("USER_ID not like", value, "userId");
            return this;
        }

        public Criteria andUserIdIn(List values) {
            addCriterion("USER_ID in", values, "userId");
            return this;
        }

        public Criteria andUserIdNotIn(List values) {
            addCriterion("USER_ID not in", values, "userId");
            return this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("USER_ID between", value1, value2, "userId");
            return this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("USER_ID not between", value1, value2, "userId");
            return this;
        }

        public Criteria andOutParkingIdIsNull() {
            addCriterion("OUT_PARKING_ID is null");
            return this;
        }

        public Criteria andOutParkingIdIsNotNull() {
            addCriterion("OUT_PARKING_ID is not null");
            return this;
        }

        public Criteria andOutParkingIdEqualTo(String value) {
            addCriterion("OUT_PARKING_ID =", value, "outParkingId");
            return this;
        }

        public Criteria andOutParkingIdNotEqualTo(String value) {
            addCriterion("OUT_PARKING_ID <>", value, "outParkingId");
            return this;
        }

        public Criteria andOutParkingIdGreaterThan(String value) {
            addCriterion("OUT_PARKING_ID >", value, "outParkingId");
            return this;
        }

        public Criteria andOutParkingIdGreaterThanOrEqualTo(String value) {
            addCriterion("OUT_PARKING_ID >=", value, "outParkingId");
            return this;
        }

        public Criteria andOutParkingIdLessThan(String value) {
            addCriterion("OUT_PARKING_ID <", value, "outParkingId");
            return this;
        }

        public Criteria andOutParkingIdLessThanOrEqualTo(String value) {
            addCriterion("OUT_PARKING_ID <=", value, "outParkingId");
            return this;
        }

        public Criteria andOutParkingIdLike(String value) {
            addCriterion("OUT_PARKING_ID like", value, "outParkingId");
            return this;
        }

        public Criteria andOutParkingIdNotLike(String value) {
            addCriterion("OUT_PARKING_ID not like", value, "outParkingId");
            return this;
        }

        public Criteria andOutParkingIdIn(List values) {
            addCriterion("OUT_PARKING_ID in", values, "outParkingId");
            return this;
        }

        public Criteria andOutParkingIdNotIn(List values) {
            addCriterion("OUT_PARKING_ID not in", values, "outParkingId");
            return this;
        }

        public Criteria andOutParkingIdBetween(String value1, String value2) {
            addCriterion("OUT_PARKING_ID between", value1, value2, "outParkingId");
            return this;
        }

        public Criteria andOutParkingIdNotBetween(String value1, String value2) {
            addCriterion("OUT_PARKING_ID not between", value1, value2, "outParkingId");
            return this;
        }

        public Criteria andParkingNameIsNull() {
            addCriterion("PARKING_NAME is null");
            return this;
        }

        public Criteria andParkingNameIsNotNull() {
            addCriterion("PARKING_NAME is not null");
            return this;
        }

        public Criteria andParkingNameEqualTo(String value) {
            addCriterion("PARKING_NAME =", value, "parkingName");
            return this;
        }

        public Criteria andParkingNameNotEqualTo(String value) {
            addCriterion("PARKING_NAME <>", value, "parkingName");
            return this;
        }

        public Criteria andParkingNameGreaterThan(String value) {
            addCriterion("PARKING_NAME >", value, "parkingName");
            return this;
        }

        public Criteria andParkingNameGreaterThanOrEqualTo(String value) {
            addCriterion("PARKING_NAME >=", value, "parkingName");
            return this;
        }

        public Criteria andParkingNameLessThan(String value) {
            addCriterion("PARKING_NAME <", value, "parkingName");
            return this;
        }

        public Criteria andParkingNameLessThanOrEqualTo(String value) {
            addCriterion("PARKING_NAME <=", value, "parkingName");
            return this;
        }

        public Criteria andParkingNameLike(String value) {
            addCriterion("PARKING_NAME like", value, "parkingName");
            return this;
        }

        public Criteria andParkingNameNotLike(String value) {
            addCriterion("PARKING_NAME not like", value, "parkingName");
            return this;
        }

        public Criteria andParkingNameIn(List values) {
            addCriterion("PARKING_NAME in", values, "parkingName");
            return this;
        }

        public Criteria andParkingNameNotIn(List values) {
            addCriterion("PARKING_NAME not in", values, "parkingName");
            return this;
        }

        public Criteria andParkingNameBetween(String value1, String value2) {
            addCriterion("PARKING_NAME between", value1, value2, "parkingName");
            return this;
        }

        public Criteria andParkingNameNotBetween(String value1, String value2) {
            addCriterion("PARKING_NAME not between", value1, value2, "parkingName");
            return this;
        }

        public Criteria andCarNumberIsNull() {
            addCriterion("CAR_NUMBER is null");
            return this;
        }

        public Criteria andCarNumberIsNotNull() {
            addCriterion("CAR_NUMBER is not null");
            return this;
        }

        public Criteria andCarNumberEqualTo(String value) {
            addCriterion("CAR_NUMBER =", value, "carNumber");
            return this;
        }

        public Criteria andCarNumberNotEqualTo(String value) {
            addCriterion("CAR_NUMBER <>", value, "carNumber");
            return this;
        }

        public Criteria andCarNumberGreaterThan(String value) {
            addCriterion("CAR_NUMBER >", value, "carNumber");
            return this;
        }

        public Criteria andCarNumberGreaterThanOrEqualTo(String value) {
            addCriterion("CAR_NUMBER >=", value, "carNumber");
            return this;
        }

        public Criteria andCarNumberLessThan(String value) {
            addCriterion("CAR_NUMBER <", value, "carNumber");
            return this;
        }

        public Criteria andCarNumberLessThanOrEqualTo(String value) {
            addCriterion("CAR_NUMBER <=", value, "carNumber");
            return this;
        }

        public Criteria andCarNumberLike(String value) {
            addCriterion("CAR_NUMBER like", value, "carNumber");
            return this;
        }

        public Criteria andCarNumberNotLike(String value) {
            addCriterion("CAR_NUMBER not like", value, "carNumber");
            return this;
        }

        public Criteria andCarNumberIn(List values) {
            addCriterion("CAR_NUMBER in", values, "carNumber");
            return this;
        }

        public Criteria andCarNumberNotIn(List values) {
            addCriterion("CAR_NUMBER not in", values, "carNumber");
            return this;
        }

        public Criteria andCarNumberBetween(String value1, String value2) {
            addCriterion("CAR_NUMBER between", value1, value2, "carNumber");
            return this;
        }

        public Criteria andCarNumberNotBetween(String value1, String value2) {
            addCriterion("CAR_NUMBER not between", value1, value2, "carNumber");
            return this;
        }

        public Criteria andOutOrderNoIsNull() {
            addCriterion("OUT_ORDER_NO is null");
            return this;
        }

        public Criteria andOutOrderNoIsNotNull() {
            addCriterion("OUT_ORDER_NO is not null");
            return this;
        }

        public Criteria andOutOrderNoEqualTo(String value) {
            addCriterion("OUT_ORDER_NO =", value, "outOrderNo");
            return this;
        }

        public Criteria andOutOrderNoNotEqualTo(String value) {
            addCriterion("OUT_ORDER_NO <>", value, "outOrderNo");
            return this;
        }

        public Criteria andOutOrderNoGreaterThan(String value) {
            addCriterion("OUT_ORDER_NO >", value, "outOrderNo");
            return this;
        }

        public Criteria andOutOrderNoGreaterThanOrEqualTo(String value) {
            addCriterion("OUT_ORDER_NO >=", value, "outOrderNo");
            return this;
        }

        public Criteria andOutOrderNoLessThan(String value) {
            addCriterion("OUT_ORDER_NO <", value, "outOrderNo");
            return this;
        }

        public Criteria andOutOrderNoLessThanOrEqualTo(String value) {
            addCriterion("OUT_ORDER_NO <=", value, "outOrderNo");
            return this;
        }

        public Criteria andOutOrderNoLike(String value) {
            addCriterion("OUT_ORDER_NO like", value, "outOrderNo");
            return this;
        }

        public Criteria andOutOrderNoNotLike(String value) {
            addCriterion("OUT_ORDER_NO not like", value, "outOrderNo");
            return this;
        }

        public Criteria andOutOrderNoIn(List values) {
            addCriterion("OUT_ORDER_NO in", values, "outOrderNo");
            return this;
        }

        public Criteria andOutOrderNoNotIn(List values) {
            addCriterion("OUT_ORDER_NO not in", values, "outOrderNo");
            return this;
        }

        public Criteria andOutOrderNoBetween(String value1, String value2) {
            addCriterion("OUT_ORDER_NO between", value1, value2, "outOrderNo");
            return this;
        }

        public Criteria andOutOrderNoNotBetween(String value1, String value2) {
            addCriterion("OUT_ORDER_NO not between", value1, value2, "outOrderNo");
            return this;
        }

        public Criteria andOrderStatusIsNull() {
            addCriterion("ORDER_STATUS is null");
            return this;
        }

        public Criteria andOrderStatusIsNotNull() {
            addCriterion("ORDER_STATUS is not null");
            return this;
        }

        public Criteria andOrderStatusEqualTo(String value) {
            addCriterion("ORDER_STATUS =", value, "orderStatus");
            return this;
        }

        public Criteria andOrderStatusNotEqualTo(String value) {
            addCriterion("ORDER_STATUS <>", value, "orderStatus");
            return this;
        }

        public Criteria andOrderStatusGreaterThan(String value) {
            addCriterion("ORDER_STATUS >", value, "orderStatus");
            return this;
        }

        public Criteria andOrderStatusGreaterThanOrEqualTo(String value) {
            addCriterion("ORDER_STATUS >=", value, "orderStatus");
            return this;
        }

        public Criteria andOrderStatusLessThan(String value) {
            addCriterion("ORDER_STATUS <", value, "orderStatus");
            return this;
        }

        public Criteria andOrderStatusLessThanOrEqualTo(String value) {
            addCriterion("ORDER_STATUS <=", value, "orderStatus");
            return this;
        }

        public Criteria andOrderStatusLike(String value) {
            addCriterion("ORDER_STATUS like", value, "orderStatus");
            return this;
        }

        public Criteria andOrderStatusNotLike(String value) {
            addCriterion("ORDER_STATUS not like", value, "orderStatus");
            return this;
        }

        public Criteria andOrderStatusIn(List values) {
            addCriterion("ORDER_STATUS in", values, "orderStatus");
            return this;
        }

        public Criteria andOrderStatusNotIn(List values) {
            addCriterion("ORDER_STATUS not in", values, "orderStatus");
            return this;
        }

        public Criteria andOrderStatusBetween(String value1, String value2) {
            addCriterion("ORDER_STATUS between", value1, value2, "orderStatus");
            return this;
        }

        public Criteria andOrderStatusNotBetween(String value1, String value2) {
            addCriterion("ORDER_STATUS not between", value1, value2, "orderStatus");
            return this;
        }

        public Criteria andOrderTimeIsNull() {
            addCriterion("ORDER_TIME is null");
            return this;
        }

        public Criteria andOrderTimeIsNotNull() {
            addCriterion("ORDER_TIME is not null");
            return this;
        }

        public Criteria andOrderTimeEqualTo(String value) {
            addCriterion("ORDER_TIME =", value, "orderTime");
            return this;
        }

        public Criteria andOrderTimeNotEqualTo(String value) {
            addCriterion("ORDER_TIME <>", value, "orderTime");
            return this;
        }

        public Criteria andOrderTimeGreaterThan(String value) {
            addCriterion("ORDER_TIME >", value, "orderTime");
            return this;
        }

        public Criteria andOrderTimeGreaterThanOrEqualTo(String value) {
            addCriterion("ORDER_TIME >=", value, "orderTime");
            return this;
        }

        public Criteria andOrderTimeLessThan(String value) {
            addCriterion("ORDER_TIME <", value, "orderTime");
            return this;
        }

        public Criteria andOrderTimeLessThanOrEqualTo(String value) {
            addCriterion("ORDER_TIME <=", value, "orderTime");
            return this;
        }

        public Criteria andOrderTimeLike(String value) {
            addCriterion("ORDER_TIME like", value, "orderTime");
            return this;
        }

        public Criteria andOrderTimeNotLike(String value) {
            addCriterion("ORDER_TIME not like", value, "orderTime");
            return this;
        }

        public Criteria andOrderTimeIn(List values) {
            addCriterion("ORDER_TIME in", values, "orderTime");
            return this;
        }

        public Criteria andOrderTimeNotIn(List values) {
            addCriterion("ORDER_TIME not in", values, "orderTime");
            return this;
        }

        public Criteria andOrderTimeBetween(String value1, String value2) {
            addCriterion("ORDER_TIME between", value1, value2, "orderTime");
            return this;
        }

        public Criteria andOrderTimeNotBetween(String value1, String value2) {
            addCriterion("ORDER_TIME not between", value1, value2, "orderTime");
            return this;
        }

        public Criteria andPayTimeIsNull() {
            addCriterion("PAY_TIME is null");
            return this;
        }

        public Criteria andPayTimeIsNotNull() {
            addCriterion("PAY_TIME is not null");
            return this;
        }

        public Criteria andPayTimeEqualTo(String value) {
            addCriterion("PAY_TIME =", value, "payTime");
            return this;
        }

        public Criteria andPayTimeNotEqualTo(String value) {
            addCriterion("PAY_TIME <>", value, "payTime");
            return this;
        }

        public Criteria andPayTimeGreaterThan(String value) {
            addCriterion("PAY_TIME >", value, "payTime");
            return this;
        }

        public Criteria andPayTimeGreaterThanOrEqualTo(String value) {
            addCriterion("PAY_TIME >=", value, "payTime");
            return this;
        }

        public Criteria andPayTimeLessThan(String value) {
            addCriterion("PAY_TIME <", value, "payTime");
            return this;
        }

        public Criteria andPayTimeLessThanOrEqualTo(String value) {
            addCriterion("PAY_TIME <=", value, "payTime");
            return this;
        }

        public Criteria andPayTimeLike(String value) {
            addCriterion("PAY_TIME like", value, "payTime");
            return this;
        }

        public Criteria andPayTimeNotLike(String value) {
            addCriterion("PAY_TIME not like", value, "payTime");
            return this;
        }

        public Criteria andPayTimeIn(List values) {
            addCriterion("PAY_TIME in", values, "payTime");
            return this;
        }

        public Criteria andPayTimeNotIn(List values) {
            addCriterion("PAY_TIME not in", values, "payTime");
            return this;
        }

        public Criteria andPayTimeBetween(String value1, String value2) {
            addCriterion("PAY_TIME between", value1, value2, "payTime");
            return this;
        }

        public Criteria andPayTimeNotBetween(String value1, String value2) {
            addCriterion("PAY_TIME not between", value1, value2, "payTime");
            return this;
        }

        public Criteria andPayTypeIsNull() {
            addCriterion("PAY_TYPE is null");
            return this;
        }

        public Criteria andPayTypeIsNotNull() {
            addCriterion("PAY_TYPE is not null");
            return this;
        }

        public Criteria andPayTypeEqualTo(String value) {
            addCriterion("PAY_TYPE =", value, "payType");
            return this;
        }

        public Criteria andPayTypeNotEqualTo(String value) {
            addCriterion("PAY_TYPE <>", value, "payType");
            return this;
        }

        public Criteria andPayTypeGreaterThan(String value) {
            addCriterion("PAY_TYPE >", value, "payType");
            return this;
        }

        public Criteria andPayTypeGreaterThanOrEqualTo(String value) {
            addCriterion("PAY_TYPE >=", value, "payType");
            return this;
        }

        public Criteria andPayTypeLessThan(String value) {
            addCriterion("PAY_TYPE <", value, "payType");
            return this;
        }

        public Criteria andPayTypeLessThanOrEqualTo(String value) {
            addCriterion("PAY_TYPE <=", value, "payType");
            return this;
        }

        public Criteria andPayTypeLike(String value) {
            addCriterion("PAY_TYPE like", value, "payType");
            return this;
        }

        public Criteria andPayTypeNotLike(String value) {
            addCriterion("PAY_TYPE not like", value, "payType");
            return this;
        }

        public Criteria andPayTypeIn(List values) {
            addCriterion("PAY_TYPE in", values, "payType");
            return this;
        }

        public Criteria andPayTypeNotIn(List values) {
            addCriterion("PAY_TYPE not in", values, "payType");
            return this;
        }

        public Criteria andPayTypeBetween(String value1, String value2) {
            addCriterion("PAY_TYPE between", value1, value2, "payType");
            return this;
        }

        public Criteria andPayTypeNotBetween(String value1, String value2) {
            addCriterion("PAY_TYPE not between", value1, value2, "payType");
            return this;
        }

        public Criteria andPayMoneyIsNull() {
            addCriterion("PAY_MONEY is null");
            return this;
        }

        public Criteria andPayMoneyIsNotNull() {
            addCriterion("PAY_MONEY is not null");
            return this;
        }

        public Criteria andPayMoneyEqualTo(String value) {
            addCriterion("PAY_MONEY =", value, "payMoney");
            return this;
        }

        public Criteria andPayMoneyNotEqualTo(String value) {
            addCriterion("PAY_MONEY <>", value, "payMoney");
            return this;
        }

        public Criteria andPayMoneyGreaterThan(String value) {
            addCriterion("PAY_MONEY >", value, "payMoney");
            return this;
        }

        public Criteria andPayMoneyGreaterThanOrEqualTo(String value) {
            addCriterion("PAY_MONEY >=", value, "payMoney");
            return this;
        }

        public Criteria andPayMoneyLessThan(String value) {
            addCriterion("PAY_MONEY <", value, "payMoney");
            return this;
        }

        public Criteria andPayMoneyLessThanOrEqualTo(String value) {
            addCriterion("PAY_MONEY <=", value, "payMoney");
            return this;
        }

        public Criteria andPayMoneyLike(String value) {
            addCriterion("PAY_MONEY like", value, "payMoney");
            return this;
        }

        public Criteria andPayMoneyNotLike(String value) {
            addCriterion("PAY_MONEY not like", value, "payMoney");
            return this;
        }

        public Criteria andPayMoneyIn(List values) {
            addCriterion("PAY_MONEY in", values, "payMoney");
            return this;
        }

        public Criteria andPayMoneyNotIn(List values) {
            addCriterion("PAY_MONEY not in", values, "payMoney");
            return this;
        }

        public Criteria andPayMoneyBetween(String value1, String value2) {
            addCriterion("PAY_MONEY between", value1, value2, "payMoney");
            return this;
        }

        public Criteria andPayMoneyNotBetween(String value1, String value2) {
            addCriterion("PAY_MONEY not between", value1, value2, "payMoney");
            return this;
        }

        public Criteria andInTimeIsNull() {
            addCriterion("IN_TIME is null");
            return this;
        }

        public Criteria andInTimeIsNotNull() {
            addCriterion("IN_TIME is not null");
            return this;
        }

        public Criteria andInTimeEqualTo(String value) {
            addCriterion("IN_TIME =", value, "inTime");
            return this;
        }

        public Criteria andInTimeNotEqualTo(String value) {
            addCriterion("IN_TIME <>", value, "inTime");
            return this;
        }

        public Criteria andInTimeGreaterThan(String value) {
            addCriterion("IN_TIME >", value, "inTime");
            return this;
        }

        public Criteria andInTimeGreaterThanOrEqualTo(String value) {
            addCriterion("IN_TIME >=", value, "inTime");
            return this;
        }

        public Criteria andInTimeLessThan(String value) {
            addCriterion("IN_TIME <", value, "inTime");
            return this;
        }

        public Criteria andInTimeLessThanOrEqualTo(String value) {
            addCriterion("IN_TIME <=", value, "inTime");
            return this;
        }

        public Criteria andInTimeLike(String value) {
            addCriterion("IN_TIME like", value, "inTime");
            return this;
        }

        public Criteria andInTimeNotLike(String value) {
            addCriterion("IN_TIME not like", value, "inTime");
            return this;
        }

        public Criteria andInTimeIn(List values) {
            addCriterion("IN_TIME in", values, "inTime");
            return this;
        }

        public Criteria andInTimeNotIn(List values) {
            addCriterion("IN_TIME not in", values, "inTime");
            return this;
        }

        public Criteria andInTimeBetween(String value1, String value2) {
            addCriterion("IN_TIME between", value1, value2, "inTime");
            return this;
        }

        public Criteria andInTimeNotBetween(String value1, String value2) {
            addCriterion("IN_TIME not between", value1, value2, "inTime");
            return this;
        }

        public Criteria andParkingIdIsNull() {
            addCriterion("PARKING_ID is null");
            return this;
        }

        public Criteria andParkingIdIsNotNull() {
            addCriterion("PARKING_ID is not null");
            return this;
        }

        public Criteria andParkingIdEqualTo(String value) {
            addCriterion("PARKING_ID =", value, "parkingId");
            return this;
        }

        public Criteria andParkingIdNotEqualTo(String value) {
            addCriterion("PARKING_ID <>", value, "parkingId");
            return this;
        }

        public Criteria andParkingIdGreaterThan(String value) {
            addCriterion("PARKING_ID >", value, "parkingId");
            return this;
        }

        public Criteria andParkingIdGreaterThanOrEqualTo(String value) {
            addCriterion("PARKING_ID >=", value, "parkingId");
            return this;
        }

        public Criteria andParkingIdLessThan(String value) {
            addCriterion("PARKING_ID <", value, "parkingId");
            return this;
        }

        public Criteria andParkingIdLessThanOrEqualTo(String value) {
            addCriterion("PARKING_ID <=", value, "parkingId");
            return this;
        }

        public Criteria andParkingIdLike(String value) {
            addCriterion("PARKING_ID like", value, "parkingId");
            return this;
        }

        public Criteria andParkingIdNotLike(String value) {
            addCriterion("PARKING_ID not like", value, "parkingId");
            return this;
        }

        public Criteria andParkingIdIn(List values) {
            addCriterion("PARKING_ID in", values, "parkingId");
            return this;
        }

        public Criteria andParkingIdNotIn(List values) {
            addCriterion("PARKING_ID not in", values, "parkingId");
            return this;
        }

        public Criteria andParkingIdBetween(String value1, String value2) {
            addCriterion("PARKING_ID between", value1, value2, "parkingId");
            return this;
        }

        public Criteria andParkingIdNotBetween(String value1, String value2) {
            addCriterion("PARKING_ID not between", value1, value2, "parkingId");
            return this;
        }

        public Criteria andInDurationIsNull() {
            addCriterion("IN_DURATION is null");
            return this;
        }

        public Criteria andInDurationIsNotNull() {
            addCriterion("IN_DURATION is not null");
            return this;
        }

        public Criteria andInDurationEqualTo(String value) {
            addCriterion("IN_DURATION =", value, "inDuration");
            return this;
        }

        public Criteria andInDurationNotEqualTo(String value) {
            addCriterion("IN_DURATION <>", value, "inDuration");
            return this;
        }

        public Criteria andInDurationGreaterThan(String value) {
            addCriterion("IN_DURATION >", value, "inDuration");
            return this;
        }

        public Criteria andInDurationGreaterThanOrEqualTo(String value) {
            addCriterion("IN_DURATION >=", value, "inDuration");
            return this;
        }

        public Criteria andInDurationLessThan(String value) {
            addCriterion("IN_DURATION <", value, "inDuration");
            return this;
        }

        public Criteria andInDurationLessThanOrEqualTo(String value) {
            addCriterion("IN_DURATION <=", value, "inDuration");
            return this;
        }

        public Criteria andInDurationLike(String value) {
            addCriterion("IN_DURATION like", value, "inDuration");
            return this;
        }

        public Criteria andInDurationNotLike(String value) {
            addCriterion("IN_DURATION not like", value, "inDuration");
            return this;
        }

        public Criteria andInDurationIn(List values) {
            addCriterion("IN_DURATION in", values, "inDuration");
            return this;
        }

        public Criteria andInDurationNotIn(List values) {
            addCriterion("IN_DURATION not in", values, "inDuration");
            return this;
        }

        public Criteria andInDurationBetween(String value1, String value2) {
            addCriterion("IN_DURATION between", value1, value2, "inDuration");
            return this;
        }

        public Criteria andInDurationNotBetween(String value1, String value2) {
            addCriterion("IN_DURATION not between", value1, value2, "inDuration");
            return this;
        }

        public Criteria andCardNumberIsNull() {
            addCriterion("CARD_NUMBER is null");
            return this;
        }

        public Criteria andCardNumberIsNotNull() {
            addCriterion("CARD_NUMBER is not null");
            return this;
        }

        public Criteria andCardNumberEqualTo(String value) {
            addCriterion("CARD_NUMBER =", value, "cardNumber");
            return this;
        }

        public Criteria andCardNumberNotEqualTo(String value) {
            addCriterion("CARD_NUMBER <>", value, "cardNumber");
            return this;
        }

        public Criteria andCardNumberGreaterThan(String value) {
            addCriterion("CARD_NUMBER >", value, "cardNumber");
            return this;
        }

        public Criteria andCardNumberGreaterThanOrEqualTo(String value) {
            addCriterion("CARD_NUMBER >=", value, "cardNumber");
            return this;
        }

        public Criteria andCardNumberLessThan(String value) {
            addCriterion("CARD_NUMBER <", value, "cardNumber");
            return this;
        }

        public Criteria andCardNumberLessThanOrEqualTo(String value) {
            addCriterion("CARD_NUMBER <=", value, "cardNumber");
            return this;
        }

        public Criteria andCardNumberLike(String value) {
            addCriterion("CARD_NUMBER like", value, "cardNumber");
            return this;
        }

        public Criteria andCardNumberNotLike(String value) {
            addCriterion("CARD_NUMBER not like", value, "cardNumber");
            return this;
        }

        public Criteria andCardNumberIn(List values) {
            addCriterion("CARD_NUMBER in", values, "cardNumber");
            return this;
        }

        public Criteria andCardNumberNotIn(List values) {
            addCriterion("CARD_NUMBER not in", values, "cardNumber");
            return this;
        }

        public Criteria andCardNumberBetween(String value1, String value2) {
            addCriterion("CARD_NUMBER between", value1, value2, "cardNumber");
            return this;
        }

        public Criteria andCardNumberNotBetween(String value1, String value2) {
            addCriterion("CARD_NUMBER not between", value1, value2, "cardNumber");
            return this;
        }
    }
}