package com.compass.vehicle.model;

import java.util.Date;

public class FreeVehicleBrandBean {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TB_FREE_VEHICLE_BRAND.FREE_VEHICLE_BRAND_ID
     *
     * @ibatorgenerated Fri Nov 17 20:17:55 CST 2017
     */
    private String freeVehicleBrandId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TB_FREE_VEHICLE_BRAND.CAR_NUMBER
     *
     * @ibatorgenerated Fri Nov 17 20:17:55 CST 2017
     */
    private String carNumber;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TB_FREE_VEHICLE_BRAND.VEHICLE_BRAND_TYPE
     *
     * @ibatorgenerated Fri Nov 17 20:17:55 CST 2017
     */
    private String vehicleBrandType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TB_FREE_VEHICLE_BRAND.IN_GATE
     *
     * @ibatorgenerated Fri Nov 17 20:17:55 CST 2017
     */
    private String inGate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TB_FREE_VEHICLE_BRAND.OUT_GATE
     *
     * @ibatorgenerated Fri Nov 17 20:17:55 CST 2017
     */
    private String outGate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TB_FREE_VEHICLE_BRAND.VEHICLE_PLACE
     *
     * @ibatorgenerated Fri Nov 17 20:17:55 CST 2017
     */
    private String vehiclePlace;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TB_FREE_VEHICLE_BRAND.SCENE_STATE
     *
     * @ibatorgenerated Fri Nov 17 20:17:55 CST 2017
     */
    private String sceneState;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TB_FREE_VEHICLE_BRAND.CAR_OWNER_NAME
     *
     * @ibatorgenerated Fri Nov 17 20:17:55 CST 2017
     */
    private String carOwnerName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TB_FREE_VEHICLE_BRAND.CAR_OWNER_ADDRES
     *
     * @ibatorgenerated Fri Nov 17 20:17:55 CST 2017
     */
    private String carOwnerAddres;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TB_FREE_VEHICLE_BRAND.CAR_OWNER_PHONE
     *
     * @ibatorgenerated Fri Nov 17 20:17:55 CST 2017
     */
    private String carOwnerPhone;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TB_FREE_VEHICLE_BRAND.CAR_OWNER_EMAIL
     *
     * @ibatorgenerated Fri Nov 17 20:17:55 CST 2017
     */
    private String carOwnerEmail;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TB_FREE_VEHICLE_BRAND.REMARK
     *
     * @ibatorgenerated Fri Nov 17 20:17:55 CST 2017
     */
    private String remark;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TB_FREE_VEHICLE_BRAND.STATE
     *
     * @ibatorgenerated Fri Nov 17 20:17:55 CST 2017
     */
    private String status;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TB_FREE_VEHICLE_BRAND.CREATE_USERID
     *
     * @ibatorgenerated Fri Nov 17 20:17:55 CST 2017
     */
    private String createUserid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TB_FREE_VEHICLE_BRAND.MODIFY_USERID
     *
     * @ibatorgenerated Fri Nov 17 20:17:55 CST 2017
     */
    private String modifyUserid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TB_FREE_VEHICLE_BRAND.CREATE_DATETIME
     *
     * @ibatorgenerated Fri Nov 17 20:17:55 CST 2017
     */
    private Date createDatetime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TB_FREE_VEHICLE_BRAND.MODIFY_DATETIME
     *
     * @ibatorgenerated Fri Nov 17 20:17:55 CST 2017
     */
    private Date modifyDatetime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TB_FREE_VEHICLE_BRAND.OUT_PARKING_ID
     *
     * @ibatorgenerated Fri Nov 17 20:17:55 CST 2017
     */
    private String outParkingId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TB_FREE_VEHICLE_BRAND.VEHICLE_BRAND
     *
     * @ibatorgenerated Fri Nov 17 20:17:55 CST 2017
     */
    private String vehicleBrand;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TB_FREE_VEHICLE_BRAND.FREE_VEHICLE_BRAND_ID
     *
     * @return the value of TB_FREE_VEHICLE_BRAND.FREE_VEHICLE_BRAND_ID
     *
     * @ibatorgenerated Fri Nov 17 20:17:55 CST 2017
     */
    public String getFreeVehicleBrandId() {
        return freeVehicleBrandId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TB_FREE_VEHICLE_BRAND.FREE_VEHICLE_BRAND_ID
     *
     * @param freeVehicleBrandId the value for TB_FREE_VEHICLE_BRAND.FREE_VEHICLE_BRAND_ID
     *
     * @ibatorgenerated Fri Nov 17 20:17:55 CST 2017
     */
    public void setFreeVehicleBrandId(String freeVehicleBrandId) {
        this.freeVehicleBrandId = freeVehicleBrandId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TB_FREE_VEHICLE_BRAND.CAR_NUMBER
     *
     * @return the value of TB_FREE_VEHICLE_BRAND.CAR_NUMBER
     *
     * @ibatorgenerated Fri Nov 17 20:17:55 CST 2017
     */
    public String getCarNumber() {
        return carNumber;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TB_FREE_VEHICLE_BRAND.CAR_NUMBER
     *
     * @param carNumber the value for TB_FREE_VEHICLE_BRAND.CAR_NUMBER
     *
     * @ibatorgenerated Fri Nov 17 20:17:55 CST 2017
     */
    public void setCarNumber(String carNumber) {
        this.carNumber = carNumber;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TB_FREE_VEHICLE_BRAND.VEHICLE_BRAND_TYPE
     *
     * @return the value of TB_FREE_VEHICLE_BRAND.VEHICLE_BRAND_TYPE
     *
     * @ibatorgenerated Fri Nov 17 20:17:55 CST 2017
     */
    public String getVehicleBrandType() {
        return vehicleBrandType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TB_FREE_VEHICLE_BRAND.VEHICLE_BRAND_TYPE
     *
     * @param vehicleBrandType the value for TB_FREE_VEHICLE_BRAND.VEHICLE_BRAND_TYPE
     *
     * @ibatorgenerated Fri Nov 17 20:17:55 CST 2017
     */
    public void setVehicleBrandType(String vehicleBrandType) {
        this.vehicleBrandType = vehicleBrandType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TB_FREE_VEHICLE_BRAND.IN_GATE
     *
     * @return the value of TB_FREE_VEHICLE_BRAND.IN_GATE
     *
     * @ibatorgenerated Fri Nov 17 20:17:55 CST 2017
     */
    public String getInGate() {
        return inGate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TB_FREE_VEHICLE_BRAND.IN_GATE
     *
     * @param inGate the value for TB_FREE_VEHICLE_BRAND.IN_GATE
     *
     * @ibatorgenerated Fri Nov 17 20:17:55 CST 2017
     */
    public void setInGate(String inGate) {
        this.inGate = inGate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TB_FREE_VEHICLE_BRAND.OUT_GATE
     *
     * @return the value of TB_FREE_VEHICLE_BRAND.OUT_GATE
     *
     * @ibatorgenerated Fri Nov 17 20:17:55 CST 2017
     */
    public String getOutGate() {
        return outGate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TB_FREE_VEHICLE_BRAND.OUT_GATE
     *
     * @param outGate the value for TB_FREE_VEHICLE_BRAND.OUT_GATE
     *
     * @ibatorgenerated Fri Nov 17 20:17:55 CST 2017
     */
    public void setOutGate(String outGate) {
        this.outGate = outGate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TB_FREE_VEHICLE_BRAND.VEHICLE_PLACE
     *
     * @return the value of TB_FREE_VEHICLE_BRAND.VEHICLE_PLACE
     *
     * @ibatorgenerated Fri Nov 17 20:17:55 CST 2017
     */
    public String getVehiclePlace() {
        return vehiclePlace;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TB_FREE_VEHICLE_BRAND.VEHICLE_PLACE
     *
     * @param vehiclePlace the value for TB_FREE_VEHICLE_BRAND.VEHICLE_PLACE
     *
     * @ibatorgenerated Fri Nov 17 20:17:55 CST 2017
     */
    public void setVehiclePlace(String vehiclePlace) {
        this.vehiclePlace = vehiclePlace;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TB_FREE_VEHICLE_BRAND.SCENE_STATE
     *
     * @return the value of TB_FREE_VEHICLE_BRAND.SCENE_STATE
     *
     * @ibatorgenerated Fri Nov 17 20:17:55 CST 2017
     */
    public String getSceneState() {
        return sceneState;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TB_FREE_VEHICLE_BRAND.SCENE_STATE
     *
     * @param sceneState the value for TB_FREE_VEHICLE_BRAND.SCENE_STATE
     *
     * @ibatorgenerated Fri Nov 17 20:17:55 CST 2017
     */
    public void setSceneState(String sceneState) {
        this.sceneState = sceneState;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TB_FREE_VEHICLE_BRAND.CAR_OWNER_NAME
     *
     * @return the value of TB_FREE_VEHICLE_BRAND.CAR_OWNER_NAME
     *
     * @ibatorgenerated Fri Nov 17 20:17:55 CST 2017
     */
    public String getCarOwnerName() {
        return carOwnerName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TB_FREE_VEHICLE_BRAND.CAR_OWNER_NAME
     *
     * @param carOwnerName the value for TB_FREE_VEHICLE_BRAND.CAR_OWNER_NAME
     *
     * @ibatorgenerated Fri Nov 17 20:17:55 CST 2017
     */
    public void setCarOwnerName(String carOwnerName) {
        this.carOwnerName = carOwnerName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TB_FREE_VEHICLE_BRAND.CAR_OWNER_ADDRES
     *
     * @return the value of TB_FREE_VEHICLE_BRAND.CAR_OWNER_ADDRES
     *
     * @ibatorgenerated Fri Nov 17 20:17:55 CST 2017
     */
    public String getCarOwnerAddres() {
        return carOwnerAddres;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TB_FREE_VEHICLE_BRAND.CAR_OWNER_ADDRES
     *
     * @param carOwnerAddres the value for TB_FREE_VEHICLE_BRAND.CAR_OWNER_ADDRES
     *
     * @ibatorgenerated Fri Nov 17 20:17:55 CST 2017
     */
    public void setCarOwnerAddres(String carOwnerAddres) {
        this.carOwnerAddres = carOwnerAddres;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TB_FREE_VEHICLE_BRAND.CAR_OWNER_PHONE
     *
     * @return the value of TB_FREE_VEHICLE_BRAND.CAR_OWNER_PHONE
     *
     * @ibatorgenerated Fri Nov 17 20:17:55 CST 2017
     */
    public String getCarOwnerPhone() {
        return carOwnerPhone;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TB_FREE_VEHICLE_BRAND.CAR_OWNER_PHONE
     *
     * @param carOwnerPhone the value for TB_FREE_VEHICLE_BRAND.CAR_OWNER_PHONE
     *
     * @ibatorgenerated Fri Nov 17 20:17:55 CST 2017
     */
    public void setCarOwnerPhone(String carOwnerPhone) {
        this.carOwnerPhone = carOwnerPhone;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TB_FREE_VEHICLE_BRAND.CAR_OWNER_EMAIL
     *
     * @return the value of TB_FREE_VEHICLE_BRAND.CAR_OWNER_EMAIL
     *
     * @ibatorgenerated Fri Nov 17 20:17:55 CST 2017
     */
    public String getCarOwnerEmail() {
        return carOwnerEmail;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TB_FREE_VEHICLE_BRAND.CAR_OWNER_EMAIL
     *
     * @param carOwnerEmail the value for TB_FREE_VEHICLE_BRAND.CAR_OWNER_EMAIL
     *
     * @ibatorgenerated Fri Nov 17 20:17:55 CST 2017
     */
    public void setCarOwnerEmail(String carOwnerEmail) {
        this.carOwnerEmail = carOwnerEmail;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TB_FREE_VEHICLE_BRAND.REMARK
     *
     * @return the value of TB_FREE_VEHICLE_BRAND.REMARK
     *
     * @ibatorgenerated Fri Nov 17 20:17:55 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TB_FREE_VEHICLE_BRAND.REMARK
     *
     * @param remark the value for TB_FREE_VEHICLE_BRAND.REMARK
     *
     * @ibatorgenerated Fri Nov 17 20:17:55 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	/**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TB_FREE_VEHICLE_BRAND.CREATE_USERID
     *
     * @return the value of TB_FREE_VEHICLE_BRAND.CREATE_USERID
     *
     * @ibatorgenerated Fri Nov 17 20:17:55 CST 2017
     */
    public String getCreateUserid() {
        return createUserid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TB_FREE_VEHICLE_BRAND.CREATE_USERID
     *
     * @param createUserid the value for TB_FREE_VEHICLE_BRAND.CREATE_USERID
     *
     * @ibatorgenerated Fri Nov 17 20:17:55 CST 2017
     */
    public void setCreateUserid(String createUserid) {
        this.createUserid = createUserid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TB_FREE_VEHICLE_BRAND.MODIFY_USERID
     *
     * @return the value of TB_FREE_VEHICLE_BRAND.MODIFY_USERID
     *
     * @ibatorgenerated Fri Nov 17 20:17:55 CST 2017
     */
    public String getModifyUserid() {
        return modifyUserid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TB_FREE_VEHICLE_BRAND.MODIFY_USERID
     *
     * @param modifyUserid the value for TB_FREE_VEHICLE_BRAND.MODIFY_USERID
     *
     * @ibatorgenerated Fri Nov 17 20:17:55 CST 2017
     */
    public void setModifyUserid(String modifyUserid) {
        this.modifyUserid = modifyUserid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TB_FREE_VEHICLE_BRAND.CREATE_DATETIME
     *
     * @return the value of TB_FREE_VEHICLE_BRAND.CREATE_DATETIME
     *
     * @ibatorgenerated Fri Nov 17 20:17:55 CST 2017
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TB_FREE_VEHICLE_BRAND.CREATE_DATETIME
     *
     * @param createDatetime the value for TB_FREE_VEHICLE_BRAND.CREATE_DATETIME
     *
     * @ibatorgenerated Fri Nov 17 20:17:55 CST 2017
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TB_FREE_VEHICLE_BRAND.MODIFY_DATETIME
     *
     * @return the value of TB_FREE_VEHICLE_BRAND.MODIFY_DATETIME
     *
     * @ibatorgenerated Fri Nov 17 20:17:55 CST 2017
     */
    public Date getModifyDatetime() {
        return modifyDatetime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TB_FREE_VEHICLE_BRAND.MODIFY_DATETIME
     *
     * @param modifyDatetime the value for TB_FREE_VEHICLE_BRAND.MODIFY_DATETIME
     *
     * @ibatorgenerated Fri Nov 17 20:17:55 CST 2017
     */
    public void setModifyDatetime(Date modifyDatetime) {
        this.modifyDatetime = modifyDatetime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TB_FREE_VEHICLE_BRAND.OUT_PARKING_ID
     *
     * @return the value of TB_FREE_VEHICLE_BRAND.OUT_PARKING_ID
     *
     * @ibatorgenerated Fri Nov 17 20:17:55 CST 2017
     */
    public String getOutParkingId() {
        return outParkingId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TB_FREE_VEHICLE_BRAND.OUT_PARKING_ID
     *
     * @param outParkingId the value for TB_FREE_VEHICLE_BRAND.OUT_PARKING_ID
     *
     * @ibatorgenerated Fri Nov 17 20:17:55 CST 2017
     */
    public void setOutParkingId(String outParkingId) {
        this.outParkingId = outParkingId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TB_FREE_VEHICLE_BRAND.VEHICLE_BRAND
     *
     * @return the value of TB_FREE_VEHICLE_BRAND.VEHICLE_BRAND
     *
     * @ibatorgenerated Fri Nov 17 20:17:55 CST 2017
     */
    public String getVehicleBrand() {
        return vehicleBrand;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TB_FREE_VEHICLE_BRAND.VEHICLE_BRAND
     *
     * @param vehicleBrand the value for TB_FREE_VEHICLE_BRAND.VEHICLE_BRAND
     *
     * @ibatorgenerated Fri Nov 17 20:17:55 CST 2017
     */
    public void setVehicleBrand(String vehicleBrand) {
        this.vehicleBrand = vehicleBrand;
    }
    
    private Integer start;
	private Integer end;
	private String inStatus;

	public Integer getStart() {
		return start;
	}

	public void setStart(Integer start) {
		this.start = start;
	}

	public Integer getEnd() {
		return end;
	}

	public void setEnd(Integer end) {
		this.end = end;
	}

	public String getInStatus() {
		return inStatus;
	}

	public void setInStatus(String inStatus) {
		this.inStatus = inStatus;
	}
}