package com.compass.vehicle.model;

public class VehicleBean {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TB_VEHICLE.CAR_ID
     *
     * @abatorgenerated Sun Oct 29 13:42:45 CST 2017
     */
    private String carId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TB_VEHICLE.CAR_NUMBER
     *
     * @abatorgenerated Sun Oct 29 13:42:45 CST 2017
     */
    private String carNumber;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TB_VEHICLE.AUTH_TOKEN
     *
     * @abatorgenerated Sun Oct 29 13:42:45 CST 2017
     */
    private String authToken;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TB_VEHICLE.APP_AUTH_TOKEN
     *
     * @abatorgenerated Sun Oct 29 13:42:45 CST 2017
     */
    private String appAuthToken;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TB_VEHICLE.USER_ID
     *
     * @abatorgenerated Sun Oct 29 13:42:45 CST 2017
     */
    private String userId;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TB_VEHICLE.CAR_ID
     *
     * @return the value of TB_VEHICLE.CAR_ID
     *
     * @abatorgenerated Sun Oct 29 13:42:45 CST 2017
     */
    public String getCarId() {
        return carId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TB_VEHICLE.CAR_ID
     *
     * @param carId the value for TB_VEHICLE.CAR_ID
     *
     * @abatorgenerated Sun Oct 29 13:42:45 CST 2017
     */
    public void setCarId(String carId) {
        this.carId = carId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TB_VEHICLE.CAR_NUMBER
     *
     * @return the value of TB_VEHICLE.CAR_NUMBER
     *
     * @abatorgenerated Sun Oct 29 13:42:45 CST 2017
     */
    public String getCarNumber() {
        return carNumber;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TB_VEHICLE.CAR_NUMBER
     *
     * @param carNumber the value for TB_VEHICLE.CAR_NUMBER
     *
     * @abatorgenerated Sun Oct 29 13:42:45 CST 2017
     */
    public void setCarNumber(String carNumber) {
        this.carNumber = carNumber;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TB_VEHICLE.AUTH_TOKEN
     *
     * @return the value of TB_VEHICLE.AUTH_TOKEN
     *
     * @abatorgenerated Sun Oct 29 13:42:45 CST 2017
     */
    public String getAuthToken() {
        return authToken;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TB_VEHICLE.AUTH_TOKEN
     *
     * @param authToken the value for TB_VEHICLE.AUTH_TOKEN
     *
     * @abatorgenerated Sun Oct 29 13:42:45 CST 2017
     */
    public void setAuthToken(String authToken) {
        this.authToken = authToken;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TB_VEHICLE.APP_AUTH_TOKEN
     *
     * @return the value of TB_VEHICLE.APP_AUTH_TOKEN
     *
     * @abatorgenerated Sun Oct 29 13:42:45 CST 2017
     */
    public String getAppAuthToken() {
        return appAuthToken;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TB_VEHICLE.APP_AUTH_TOKEN
     *
     * @param appAuthToken the value for TB_VEHICLE.APP_AUTH_TOKEN
     *
     * @abatorgenerated Sun Oct 29 13:42:45 CST 2017
     */
    public void setAppAuthToken(String appAuthToken) {
        this.appAuthToken = appAuthToken;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TB_VEHICLE.USER_ID
     *
     * @return the value of TB_VEHICLE.USER_ID
     *
     * @abatorgenerated Sun Oct 29 13:42:45 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TB_VEHICLE.USER_ID
     *
     * @param userId the value for TB_VEHICLE.USER_ID
     *
     * @abatorgenerated Sun Oct 29 13:42:45 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }
}