package com.compass.vehicle.model;

public class VehicleBeanExample extends VehicleBean {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table TB_VEHICLE
     *
     * @abatorgenerated Sun Oct 29 13:42:45 CST 2017
     */
    public static final int EXAMPLE_IGNORE = 0;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table TB_VEHICLE
     *
     * @abatorgenerated Sun Oct 29 13:42:45 CST 2017
     */
    public static final int EXAMPLE_NULL = 1;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table TB_VEHICLE
     *
     * @abatorgenerated Sun Oct 29 13:42:45 CST 2017
     */
    public static final int EXAMPLE_NOT_NULL = 2;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table TB_VEHICLE
     *
     * @abatorgenerated Sun Oct 29 13:42:45 CST 2017
     */
    public static final int EXAMPLE_EQUALS = 3;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table TB_VEHICLE
     *
     * @abatorgenerated Sun Oct 29 13:42:45 CST 2017
     */
    public static final int EXAMPLE_NOT_EQUALS = 4;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table TB_VEHICLE
     *
     * @abatorgenerated Sun Oct 29 13:42:45 CST 2017
     */
    public static final int EXAMPLE_GREATER_THAN = 5;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table TB_VEHICLE
     *
     * @abatorgenerated Sun Oct 29 13:42:45 CST 2017
     */
    public static final int EXAMPLE_GREATER_THAN_OR_EQUAL = 6;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table TB_VEHICLE
     *
     * @abatorgenerated Sun Oct 29 13:42:45 CST 2017
     */
    public static final int EXAMPLE_LESS_THAN = 7;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table TB_VEHICLE
     *
     * @abatorgenerated Sun Oct 29 13:42:45 CST 2017
     */
    public static final int EXAMPLE_LESS_THAN_OR_EQUAL = 8;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table TB_VEHICLE
     *
     * @abatorgenerated Sun Oct 29 13:42:45 CST 2017
     */
    public static final int EXAMPLE_LIKE = 9;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table TB_VEHICLE
     *
     * @abatorgenerated Sun Oct 29 13:42:45 CST 2017
     */
    private boolean combineTypeOr;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table TB_VEHICLE
     *
     * @abatorgenerated Sun Oct 29 13:42:45 CST 2017
     */
    private int carId_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table TB_VEHICLE
     *
     * @abatorgenerated Sun Oct 29 13:42:45 CST 2017
     */
    private int carNumber_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table TB_VEHICLE
     *
     * @abatorgenerated Sun Oct 29 13:42:45 CST 2017
     */
    private int authToken_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table TB_VEHICLE
     *
     * @abatorgenerated Sun Oct 29 13:42:45 CST 2017
     */
    private int appAuthToken_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table TB_VEHICLE
     *
     * @abatorgenerated Sun Oct 29 13:42:45 CST 2017
     */
    private int userId_Indicator;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_VEHICLE
     *
     * @abatorgenerated Sun Oct 29 13:42:45 CST 2017
     */
    public void setCombineTypeOr(boolean combineTypeOr) {
        this.combineTypeOr = combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_VEHICLE
     *
     * @abatorgenerated Sun Oct 29 13:42:45 CST 2017
     */
    public boolean isCombineTypeOr() {
        return combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_VEHICLE
     *
     * @abatorgenerated Sun Oct 29 13:42:45 CST 2017
     */
    public int getCarId_Indicator() {
        return carId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_VEHICLE
     *
     * @abatorgenerated Sun Oct 29 13:42:45 CST 2017
     */
    public void setCarId_Indicator(int carId_Indicator) {
        this.carId_Indicator = carId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_VEHICLE
     *
     * @abatorgenerated Sun Oct 29 13:42:45 CST 2017
     */
    public int getCarNumber_Indicator() {
        return carNumber_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_VEHICLE
     *
     * @abatorgenerated Sun Oct 29 13:42:45 CST 2017
     */
    public void setCarNumber_Indicator(int carNumber_Indicator) {
        this.carNumber_Indicator = carNumber_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_VEHICLE
     *
     * @abatorgenerated Sun Oct 29 13:42:45 CST 2017
     */
    public int getAuthToken_Indicator() {
        return authToken_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_VEHICLE
     *
     * @abatorgenerated Sun Oct 29 13:42:45 CST 2017
     */
    public void setAuthToken_Indicator(int authToken_Indicator) {
        this.authToken_Indicator = authToken_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_VEHICLE
     *
     * @abatorgenerated Sun Oct 29 13:42:45 CST 2017
     */
    public int getAppAuthToken_Indicator() {
        return appAuthToken_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_VEHICLE
     *
     * @abatorgenerated Sun Oct 29 13:42:45 CST 2017
     */
    public void setAppAuthToken_Indicator(int appAuthToken_Indicator) {
        this.appAuthToken_Indicator = appAuthToken_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_VEHICLE
     *
     * @abatorgenerated Sun Oct 29 13:42:45 CST 2017
     */
    public int getUserId_Indicator() {
        return userId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_VEHICLE
     *
     * @abatorgenerated Sun Oct 29 13:42:45 CST 2017
     */
    public void setUserId_Indicator(int userId_Indicator) {
        this.userId_Indicator = userId_Indicator;
    }
}